<div x-show="courseStep===2" class="rounded-xl border p-4 space-y-3">
    <h4 class="font-semibold">3. Tendencia central · curso, páginas 11–18</h4>
    <p>Se comparan varios centros; ninguno se adopta por defecto. La media usa todos los valores, la mediana depende del orden y la geométrica requiere valores positivos. La moda exacta depende de repeticiones; la clase modal es el bloque más frecuente.</p>
    <p class="font-mono">Media = Σxᵢ / n · Geométrica = exp(Σln(xᵢ) / n)</p>
    <p><strong>MAPE · Mean Absolute Percentage Error (error porcentual absoluto medio).</strong> La tabla se ordena de menor a mayor MAPE; los resultados no estimables aparecen al final. Un valor menor indica menor diferencia porcentual media respecto de los datos de esta muestra, sin adoptar automáticamente ese estimador.</p>
    <?php require __DIR__.'/methodology-course-mape-academy.php'; ?>
    <p>La recortada del ejercicio toma 20 % por cola: k = piso(0,20 × n). Sólo resume los valores centrales; las muestras originales siguen conservadas. MAPE compara cada centro con estos mismos datos, no garantiza precisión fuera de la muestra.</p>
    <div class="overflow-auto"><table class="min-w-full text-left"><thead><tr><th class="p-2">Estimador</th><th class="p-2">COP/m²</th><th class="p-2">MAPE % · menor a mayor</th></tr></thead><tbody><template x-for="e in courseSortedEstimators()" :key="e.label"><tr><td class="p-2" x-text="e.label"></td><td class="p-2" x-text="courseNumber(e.value)"></td><td class="p-2" x-text="courseNumber(e.mape)"></td></tr></template></tbody></table></div>
    <p x-text="'Moda exacta: '+(courseResult.summary.modes.length?courseResult.summary.modes.map(v=>courseNumber(v)).join(', '):'sin repeticiones')"></p>
    <p x-text="'Clase modal: '+courseResult.summary.classes.filter(c=>c.frequency===Math.max(...courseResult.summary.classes.map(v=>v.frequency))).map(c=>'bloque '+c.n).join(', ')"></p>
    <p x-text="'Recortada: '+Math.floor(courseResult.valid.length*.2)+' valores por cola para este estimador; '+(courseResult.valid.length-2*Math.floor(courseResult.valid.length*.2))+' valores en su cálculo.'"></p>
</div>
<div x-show="courseStep===3" class="rounded-xl border p-4 space-y-3">
    <h4 class="font-semibold">4. Dispersión · curso, páginas 21–35</h4>
    <p>Un centro parecido puede ocultar dispersiones distintas. Se calcula la versión muestral con n−1 y se declara la unidad. Un CV alto invita a estudiar comparabilidad y mercado; no dice qué inmueble es incorrecto.</p>
    <p class="font-mono">Rango = máximo − mínimo<br>s² = Σ(xᵢ − media)² / (n − 1) · s = √s² · CV = 100 × s / |media|</p>
    <div class="overflow-auto"><table class="min-w-full text-left"><thead><tr><th class="p-2">Mínimo</th><th class="p-2">Máximo</th><th class="p-2">Rango</th><th class="p-2">Varianza</th><th class="p-2">s</th><th class="p-2">CV %</th></tr></thead><tbody><tr><template x-for="key in ['min','max','range','variance','sd','cv']" :key="key"><td class="p-2" x-text="courseNumber(courseResult.summary[key])"></td></template></tr></tbody></table></div>
    <p class="text-sm">Resolución IGAC 0941 de 2026, art. 21: límites máximos del CV (coeficiente de variación) para adoptar la media, 7,50 % urbano y 10,0 % rural, según el ámbito aplicable. Exige además revisar el mercado; estos límites no ordenan exclusiones ni validan por sí solos el avalúo. Este ejercicio no adopta una media automáticamente.</p>
    <details class="rounded-lg border p-3"><summary class="min-h-11 cursor-pointer font-semibold">Ver cálculo por inmueble</summary><div class="overflow-auto"><table class="min-w-full text-left text-sm"><thead><tr><th class="p-2">Muestra</th><th class="p-2">x − media</th><th class="p-2">(x − media)²</th></tr></thead><tbody><template x-for="r in courseResult.valid" :key="r.id"><tr><td class="p-2" x-text="r.label"></td><td class="p-2" x-text="courseNumber(r.y-courseResult.summary.mean)"></td><td class="p-2" x-text="courseNumber((r.y-courseResult.summary.mean)**2)"></td></tr></template></tbody></table></div></details>
</div>
<div x-show="courseStep===4" class="rounded-xl border p-4 space-y-3">
    <h4 class="font-semibold">5. Sensibilidad y consideraciones · curso, páginas 14, 30 y 49–50; diagnósticos complementarios</h4>
    <p>Contrasta media, mediana y recortada del paso 3. El cambio entre ellas muestra sensibilidad. Revisar un extremo no significa eliminarlo: deja la consideración y verifica el inmueble.</p>
    <p class="font-mono">RIC = Q3 − Q1 · límites exploratorios = Q1 − 1,5 RIC / Q3 + 1,5 RIC<br>MAD = mediana(|xᵢ − mediana|) · z robusto = 0,67448975 × (xᵢ − mediana) / MAD</p>
    <p class="text-sm">Señal robusta si |z| &gt; 3,5; MAD cero deja el diagnóstico no estimable. Asimetría y exceso de curtosis corregidos como Excel SKEW/KURT, con exceso normal de referencia cero. Ni el signo ni una señal deciden el valor o una exclusión.</p>
    <div class="overflow-auto"><table class="min-w-full text-left"><thead><tr><th class="p-2">Asimetría</th><th class="p-2">Exceso de curtosis</th><th class="p-2">Q1</th><th class="p-2">Q3</th><th class="p-2">MAD</th></tr></thead><tbody><tr><template x-for="key in ['skew','kurt','q1','q3','mad']" :key="key"><td class="p-2" x-text="courseNumber(courseResult.summary[key])"></td></template></tr></tbody></table></div>
    <p class="text-sm text-amber-900">Las consideraciones de este recorrido se mantienen mientras la ficha está abierta y se incluyen en la memoria descargada. Guarda esa descarga para conservarlas; todavía no se incorporan al autoguardado.</p>
    <div class="max-h-[65vh] overflow-auto"><table class="min-w-full text-left text-sm"><thead><tr><th class="p-2">Inmueble</th><th class="p-2">Valor unitario</th><th class="p-2">z robusto</th><th class="p-2">Señales</th><th class="p-2">Consideración</th></tr></thead><tbody><template x-for="r in courseResult.summary.considerations" :key="r.id"><tr class="border-t" :class="r.flags.length?'bg-amber-50':''"><td class="p-2"><p x-text="r.label"></p><button type="button" class="btn-secondary" @click="await courseReview(r.id)">Revisar inmueble</button></td><td class="p-2" x-text="courseNumber(r.y)"></td><td class="p-2" x-text="courseNumber(r.modifiedZ)"></td><td class="p-2" x-text="r.flags.join(' · ')||'Sin señales'"></td><td class="p-2"><label class="label"><span x-text="'Consideración sobre '+r.label"></span><textarea class="input min-w-64" rows="2" placeholder="Ej. revisar ubicación, área, parqueo o soporte del descuento" x-model="courseNotes[r.id]"></textarea></label></td></tr></template></tbody></table></div>
</div>
