<details x-show="courseStep===0" class="rounded-xl border p-3 space-y-3">
    <summary class="min-h-11 cursor-pointer font-semibold">Detalle por inmueble · valores, fórmulas y pendientes</summary>
    <h4 class="font-semibold">1. Base del cálculo · curso, páginas 5–10 y 19</h4>
    <p>Primero se revisan comparabilidad, evidencia, precio negociado, unidad y base de área. El descuento modifica el precio final; no es predictor. Un descuento de cero debe registrarse expresamente. En el ejercicio conservamos el área publicada y dejamos visible su revisión pendiente.</p>
    <p class="font-mono">Valor final = oferta − descuento = oferta × (1 − porcentaje / 100)<br>Valor unitario preliminar = valor final / área publicada</p>
    <p>En PH, el curso distingue el área privada y los componentes incluidos en precio, como garaje y depósito. No se deduce el valor de un garaje a partir de su cantidad. Datos supuestos siguen siendo supuestos.</p>
    <div class="max-h-[65vh] overflow-auto"><table class="min-w-full text-left text-sm"><thead><tr><th class="p-2">Inmueble</th><th class="p-2">Oferta COP</th><th class="p-2">Descuento COP</th><th class="p-2">Valor final COP</th><th class="p-2">Área m²</th><th class="p-2">Valor unitario</th><th class="p-2">Estado</th></tr></thead><tbody><template x-for="r in courseResult.rows" :key="r.id"><tr class="border-t" :class="r.reasons.length?'bg-amber-50':''"><td class="p-2"><p x-text="r.label"></p><button type="button" class="btn-secondary" @click="await courseReview(r.id)">Revisar inmueble</button></td><template x-for="key in ['offer','discount','final','area']" :key="key"><td class="p-2" x-text="courseNumber(r[key])"></td></template><td class="p-2" x-text="r.reasons.length?'Pendiente':courseNumber(r.y)"></td><td class="p-2"><p x-text="r.reasons.join(' · ')||'Disponible para el ejercicio'"></p><p class="text-amber-900" x-text="r.areaNote"></p></td></tr></template></tbody></table></div>
    <p class="text-sm">La estadística descriptiva no exige tres factores ni treinta muestras. Esos mínimos pertenecen al ejercicio de regresión. Aquí no desaparecen las pendientes.</p>
</details>
<template x-if="courseStep===1"><div class="rounded-xl border p-4 space-y-3">
    <h4 class="font-semibold">2. Bloques y distribución</h4>
    <p>Se calculan la media y el CV (coeficiente de variación) de los inmuebles de cada bloque. La tabla presenta los resultados por intervalo y marca de clase, utilizando los valores unitarios individuales.</p>
    <p class="font-mono">k = techo(log₂(n) + 1) · amplitud = (máximo − mínimo) / k<br>Marca de clase = (límite inferior + límite superior) / 2</p>
    <p class="text-sm">Agrupación mediante la regla de Sturges. Cada intervalo incluye su límite inferior y excluye el superior, salvo el último, que incluye ambos. Una serie constante forma un bloque.</p>
    <p class="rounded-lg border bg-teal-50 p-3 text-sm"><strong>Alcance del resultado:</strong> el CV por bloque es descriptivo; no constituye por sí solo un indicador de comparabilidad ni de cumplimiento normativo. Estos resultados requieren continuar con el análisis completo de la muestra. El cálculo conserva el grupo de inmuebles seleccionado.</p>
    <?php require __DIR__.'/methodology-course-blocks-academy.php'; ?>
    <div :key="courseResult.at" x-effect="coursePlot($el,courseResult.histogram)"></div>
    <div class="overflow-auto"><table class="min-w-full text-left text-sm"><thead><tr><th class="p-2">Bloque</th><th class="p-2">Intervalo COP/m²</th><th class="p-2">Marca de clase</th><th class="p-2">Frecuencia</th><th class="p-2">%</th><th class="p-2">Acumulada</th><th class="p-2">Media COP/m²</th><th class="p-2">CV descriptivo %</th></tr></thead><tbody><template x-for="c in courseResult.summary.classes" :key="c.n"><tr class="border-t"><td class="p-2" x-text="c.n"></td><td class="p-2" x-text="'['+courseNumber(c.lower)+', '+courseNumber(c.upper)+(c.closed?']':')')"></td><td class="p-2" x-text="courseNumber(c.mark)"></td><td class="p-2" x-text="c.frequency"></td><td class="p-2" x-text="courseNumber(c.percent)"></td><td class="p-2" x-text="c.cumulative"></td><td class="p-2" x-text="courseNumber(c.mean)"></td><td class="p-2" x-text="courseNumber(c.cv)"></td></tr></template></tbody></table></div>
    <template x-for="c in courseResult.summary.classes" :key="c.n"><details class="rounded-lg border p-3"><summary class="min-h-11 cursor-pointer font-semibold" x-text="'Bloque '+c.n+' · '+c.frequency+' inmuebles'"></summary><p class="text-sm" x-text="'Media del bloque: '+courseNumber(c.mean)+' COP/m² · CV descriptivo del bloque: '+(c.frequency===0?'no estimable sin inmuebles':c.frequency===1?'no estimable con un solo inmueble':courseNumber(c.cv)+' %')+' · no valida un submercado'"></p><template x-for="r in c.members" :key="r.id"><p class="flex flex-wrap items-center gap-3 mt-2"><span x-text="r.label+' · '+courseNumber(r.y)+' COP/m²'"></span><button type="button" class="btn-secondary" @click="await courseReview(r.id)">Revisar inmueble</button></p></template></details></template>
</div></template>
