<details class="my-4 rounded-xl border border-teal-200 bg-teal-50 p-4">
    <summary class="min-h-11 cursor-pointer py-2 font-semibold">? PH: parqueaderos y depósitos · captura, depuración y liquidación</summary>
    <div class="space-y-3 text-sm leading-6">
        <p><strong>M3 · Captura:</strong> conserva el precio completo publicado y registra qué incluye: unidad principal, parqueaderos, depósitos y áreas libres. Describe cantidades, áreas, fuente y naturaleza jurídica conocida: privada, matrícula independiente o común de uso exclusivo. Si la fuente informa un precio por componente, consérvalo con su soporte. Capturar no aplica descuentos.</p>
        <p><strong>Datos incompletos:</strong> completa manualmente lo que puedas corroborar con el anunciante o los documentos. Lo desconocido queda pendiente y con salvedad; no equivale a cero. Conserva ubicación, coordenadas, fotos y evidencia en «Mapas y evidencia» de esa misma muestra.</p>
        <p><strong>M4 · Depuración de comparables PH (art. 19.2.b):</strong> cuando el dato incluya garajes, depósitos, áreas libres u otras unidades privadas o comunes de uso exclusivo, la norma dispone descontar su valor del precio negociado para permitir la comparación. No establece una excepción porque todos los comparables incluyan parqueadero y depósito.</p>
        <p><strong>Sustentación del perito:</strong> identifica los componentes, investiga y documenta sus valores y el tratamiento aplicado. No uses porcentajes predeterminados ni descuentos inventados. Si falta soporte para cuantificar, deja pendiente la investigación. El criterio profesional sustenta la cuantificación; no convierte la exigencia en opcional.</p>
        <p><strong>Liquidación del inmueble avaluado (art. 36.2):</strong> verifica restricciones como servidumbres. Si el parqueadero, garaje, depósito o área libre tiene matrícula independiente, determina su valor global o por m² conforme al mercado. Si es un bien común de uso exclusivo, su valor queda implícito en el valor integral de la unidad principal y no se liquida independientemente.</p>
        <p><strong>Evita el doble conteo:</strong> depurar las muestras y liquidar el inmueble sujeto son etapas distintas. Documenta cómo pasa el resultado del análisis a la liquidación, atendiendo la naturaleza jurídica; no sumes otra vez un componente ya incluido en el valor integral.</p>
        <p><strong>Otros tratamientos:</strong> el art. 36.3 exige valorar diferenciadamente el área privada construida y la libre. Para condominios o PH físicamente asimilables a NPH, revisa la ruta especial del art. 19.2.c. No se deduce ese tratamiento del anuncio sin verificarlo.</p>
        <p class="rounded-lg bg-white p-3"><strong>Alcance actual del programa:</strong> esta ayuda no ejecuta descuentos ni liquidaciones. Los estadísticos actuales de M4 usan los precios registrados; no incorporan automáticamente negociación ni depuración de componentes y no constituyen un valor adoptado.</p>
        <p>Consulta de apoyo para el analista; no se incorpora automáticamente al texto del entregable.</p>
        <a class="inline-flex min-h-11 items-center font-semibold text-teal-800 underline" target="_blank" rel="noopener" data-no-fetch
            href="https://camacol.co/sites/default/files/descargables/IGAC-Resolucion-2026-N0000941_20260731_Diario_Oficial-N053573_20260801.pdf#page=9">Consultar artículo 36 · Diario Oficial, reproducción publicada por Camacol</a>
    </div>
    <?php $readingNumber = 19; require __DIR__ . '/valuation-methodology-article-reading.php'; ?>
</details>
