<details class="rounded-lg border bg-slate-50 p-3">
    <summary class="min-h-11 cursor-pointer font-semibold">¿Puedo calcular el CV por bloque? · explicación y revisión de atípicos</summary>
    <div class="mt-3 space-y-3">
        <p><strong>Sí, como descripción de ese bloque.</strong> El CV (coeficiente de variación) compara la dispersión con la media. Aquí se calcula con los valores unitarios individuales de los inmuebles del bloque, no con su marca de clase (punto medio del intervalo). Se necesitan al menos dos valores y una media distinta de cero.</p>
        <p><strong>Con plastilina:</strong> si escoges sólo precios entre 10 y 11 millones, ya dejaste fuera los precios alejados. Es esperable que el CV disminuya. Eso describe una franja estrecha, pero todavía no demuestra que sus inmuebles sean los comparables adecuados para tu avalúo. No se escoge una franja únicamente para obtener un CV menor.</p>
        <p><strong>Un grupo comparable necesita otra explicación.</strong> Por ejemplo, ubicación, uso o condiciones físicas y jurídicas verificadas pueden justificar estudiar grupos por separado. Primero se sustenta esa separación con características independientes del precio; después se calcula e interpreta el CV de cada grupo. Un bloque del histograma, por sí solo, no acredita un submercado.</p>
        <h5 class="font-semibold">¿Y la eliminación de atípicos que explicó el profesor?</h5>
        <p>Un atípico (dato que se aleja del comportamiento de los demás) es una señal para investigar. La Sesión 2 distingue entre detectar esa señal y justificar una exclusión:</p>
        <ol class="list-decimal pl-5 space-y-2">
            <li><strong>Revisar el dato y su fuente:</strong> precio, área, unidad, duplicados y características del inmueble. Un error comprobado se corrige con soporte; no se borra sólo por ser extremo.</li>
            <li><strong>Investigar la comparabilidad:</strong> si existe una causa documentada que lo hace no comparable, se puede excluir por esa causa. Si no existe, la señal estadística por sí sola no justifica retirarlo. Una causa documentada también puede justificar excluir un dato que no parezca extremo.</li>
            <li><strong>Conservar la trazabilidad:</strong> identificar el inmueble, la causa, la evidencia y los resultados antes y después: cantidad, media, desviación estándar y CV.</li>
            <li><strong>Mostrar sensibilidad (cuánto cambia el resultado):</strong> comparar con y sin el dato ayuda a entender su efecto. Esa comparación no equivale a autorizar su exclusión ni modifica automáticamente el grupo guardado.</li>
        </ol>
        <p><strong>Ejemplo del curso, no de tus muestras:</strong> en la Sesión 2, página 36, el ejercicio conserva 12 datos y obtiene CV de 11,30 % cuando no se verifica una diferencia normativa. Si se verifica y documenta esa diferencia que afecta la comparabilidad, retira ese inmueble: quedan 11 datos y el CV es 5,86 %. La decisión se apoya en la evidencia; la disminución del CV es una consecuencia.</p>
        <p><strong>Qué hacemos aquí:</strong> abrir los bloques sirve para examinar sus inmuebles. El CV mostrado es descriptivo y no elimina muestras. La revisión de señales está en «Sensibilidad y consideraciones». No se retiran inmuebles ni se recortan franjas sólo para alcanzar el 7,50 %; si la dispersión continúa, se estudian comparabilidad y alternativas de análisis, incluida la modelación cuando corresponda.</p>
        <button type="button" class="btn-secondary" @click="courseStep=4">Ir a Sensibilidad y consideraciones</button>
        <p class="text-sm"><strong>Fuentes académicas:</strong> Sesión 1 · Estadística en valuación, páginas 29 y 33–34; Sesión 2 · Forma, robustez y depuración, páginas 21 y 35–38. Paráfrasis del material del profesor; el histograma y sus CV por bloque son un complemento descriptivo. El fundamento jurídico y su alcance se consultan en la academia de este apartado; estas herramientas no acreditan por sí solas cumplimiento normativo.</p>
    </div>
</details>
