<div x-show="courseStep===5" class="rounded-xl border p-4 space-y-3">
    <h4 class="font-semibold">6. Precisión de la media · curso, páginas 36–46</h4>
    <p>El intervalo cuantifica la precisión de la media bajo los supuestos de muestreo. No es el rango de precios individuales, el error del avalúo ni una garantía frente a sesgo. Anuncios relacionados pueden aportar información dependiente.</p>
    <p class="font-mono">Error estándar = s / √n<br>IC = media ± t((1 + confianza)/2; n − 1) × s / √n<br>Semiancho relativo % = 100 × semiancho / |media|</p>
    <div class="overflow-auto"><table class="min-w-full text-left"><thead><tr><th class="p-2">Confianza %</th><th class="p-2">gl</th><th class="p-2">t</th><th class="p-2">Error estándar</th><th class="p-2">Semiancho</th><th class="p-2">Inferior</th><th class="p-2">Superior</th><th class="p-2">Semiancho relativo %</th></tr></thead><tbody><tr><td class="p-2" x-text="100*courseResult.summary.confidence"></td><td class="p-2" x-text="courseResult.valid.length-1"></td><template x-for="key in ['t','se','margin','lowerCI','upperCI','relativeMargin']" :key="key"><td class="p-2" x-text="courseNumber(courseResult.summary[key])"></td></template></tr></tbody></table></div>
    <p>Interpretación: en repeticiones del procedimiento, la proporción de intervalos que contiene la media poblacional corresponde al nivel elegido. La conclusión exige revisar representatividad, independencia y extremos.</p>
    <h5 class="font-semibold">Remuestreo bootstrap · complemento opcional del curso</h5>
    <p>Se extraen n valores con reemplazo, se recalculan media, mediana y CV, y se repite 10.000 veces con semilla 2026. Los intervalos percentiles muestran sensibilidad a la muestra; no crean inmuebles ni aumentan su cantidad.</p>
    <button type="button" class="btn-secondary" :disabled="!courseCurrent()||courseBootstrapBusy" @click="await courseResample()" x-text="courseBootstrapBusy?'Remuestreando…':'Ejecutar 10.000 remuestreos'"></button>
    <div x-show="courseBootstrapBusy" role="status"><progress class="w-full" max="10000" :value="courseProgress"></progress><p x-text="courseProgress+' / 10.000 remuestreos · '+Math.round(courseProgress/100)+' %'"></p></div>
    <template x-if="courseResult.bootstrap"><div><div class="overflow-auto"><table class="min-w-full text-left"><thead><tr><th class="p-2">Serie</th><th class="p-2">Inferior</th><th class="p-2">Superior</th></tr></thead><tbody><template x-for="item in [{key:'mean',label:'Media · COP/m²'},{key:'median',label:'Mediana · COP/m²'},{key:'cv',label:'CV · %'}]" :key="item.key"><tr><td class="p-2" x-text="item.label"></td><td class="p-2" x-text="courseNumber(courseResult.bootstrap[item.key][0])"></td><td class="p-2" x-text="courseNumber(courseResult.bootstrap[item.key][1])"></td></tr></template></tbody></table></div><p class="text-sm" x-text="'10.000 repeticiones · semilla '+courseResult.bootstrap.seed+' · generador Mulberry32 · confianza '+courseResult.bootstrap.confidence*100+' % · cuantiles interpolados'"></p></div></template>
</div>
<div x-show="courseStep===6" class="rounded-xl border p-4 space-y-3">
    <h4 class="font-semibold">7. Conclusión y memoria · curso, páginas 47–51</h4>
    <p>Contrasta comparabilidad, centros, dispersión, sensibilidad y precisión antes de concluir. Un dato extremo sin evidencia de no comparabilidad se conserva. Justifica cualquier decisión; este recorrido no retira muestras ni adopta un valor.</p>
    <label class="label">Conclusión del analista para el ejercicio<textarea class="input" rows="4" placeholder="Explica los bloques observados, estimadores, dispersión, limitaciones y revisiones pendientes" x-model="courseConclusion"></textarea></label>
    <p class="text-sm text-amber-900">La conclusión y las consideraciones se conservan en la descarga de esta ejecución. No se autoguardan todavía. El informe reproduce los siete pasos, base, muestras pendientes, clases, fórmulas, resultados y notas.</p>
    <button type="button" class="btn-primary" :disabled="!courseCurrent()||courseBootstrapBusy" @click="courseExport()">Descargar memoria del ejercicio</button>
    <button type="button" class="btn-secondary" @click="analysisModule='regression';regressionTab='application'">Continuar a preparar la regresión</button>
    <p>La regresión usa los valores individuales y los factores aplicados, con sus propios requisitos. Su conteo puede diferir del descriptivo; el paso Preparar y calcular mostrará el motivo por inmueble.</p>
</div>
