<div x-show="courseStep===0" class="rounded-xl border p-4 space-y-3">
    <h4 class="font-semibold">1. Preparar la muestra · curso, páginas 5–10 y 19</h4>
    <p>Primero se revisan comparabilidad, evidencia, precio negociado, unidad y base de área. El descuento modifica el precio final; no es predictor. Un descuento de cero debe registrarse expresamente. En el ejercicio conservamos el área publicada y dejamos visible su revisión pendiente.</p>
    <p class="font-mono">Valor final = oferta − descuento = oferta × (1 − porcentaje / 100)<br>Valor unitario preliminar = valor final / área publicada</p>
    <p>En PH, el curso distingue el área privada y los componentes incluidos en precio, como garaje y depósito. No se deduce el valor de un garaje a partir de su cantidad. Datos supuestos siguen siendo supuestos.</p>
    <div class="max-h-[65vh] overflow-auto"><table class="min-w-full text-left text-sm"><thead><tr><th class="p-2">Inmueble</th><th class="p-2">Oferta COP</th><th class="p-2">Descuento COP</th><th class="p-2">Valor final COP</th><th class="p-2">Área m²</th><th class="p-2">Valor unitario</th><th class="p-2">Estado</th></tr></thead><tbody><template x-for="r in courseResult.rows" :key="r.id"><tr class="border-t" :class="r.reasons.length?'bg-amber-50':''"><td class="p-2"><p x-text="r.label"></p><button type="button" class="btn-secondary" @click="await courseReview(r.id)">Revisar inmueble</button></td><template x-for="key in ['offer','discount','final','area']" :key="key"><td class="p-2" x-text="courseNumber(r[key])"></td></template><td class="p-2" x-text="r.reasons.length?'Pendiente':courseNumber(r.y)"></td><td class="p-2"><p x-text="r.reasons.join(' · ')||'Disponible para el ejercicio'"></p><p class="text-amber-900" x-text="r.areaNote"></p></td></tr></template></tbody></table></div>
    <p class="text-sm">La estadística descriptiva no exige tres factores ni treinta muestras. Esos mínimos pertenecen al ejercicio de regresión. Aquí no desaparecen las pendientes.</p>
</div>
<template x-if="courseStep===1"><div class="rounded-xl border p-4 space-y-3">
    <h4 class="font-semibold">2. Bloques y distribución · complemento al curso</h4>
    <p>El histograma muestra concentración, huecos y posibles bandas. Cada bloque conserva los inmuebles que contiene. Las marcas de clase resumen intervalos, no reemplazan los valores originales en los demás cálculos.</p>
    <p class="font-mono">k = techo(log₂(n) + 1) · amplitud = (máximo − mínimo) / k<br>Marca de clase = (límite inferior + límite superior) / 2</p>
    <p class="text-sm">Regla de Sturges para este ejercicio. Intervalos [inferior, superior), último cerrado. Una serie constante forma un bloque. La página 34 del curso indica que un submercado requiere atributos independientes del precio; un bloque del histograma sólo orienta la revisión.</p>
    <div :key="courseResult.at" x-effect="coursePlot($el,courseResult.histogram)"></div>
    <div class="overflow-auto"><table class="min-w-full text-left text-sm"><thead><tr><th class="p-2">Bloque</th><th class="p-2">Intervalo COP/m²</th><th class="p-2">Marca</th><th class="p-2">Frecuencia</th><th class="p-2">%</th><th class="p-2">Acumulada</th></tr></thead><tbody><template x-for="c in courseResult.summary.classes" :key="c.n"><tr class="border-t"><td class="p-2" x-text="c.n"></td><td class="p-2" x-text="'['+courseNumber(c.lower)+', '+courseNumber(c.upper)+(c.closed?']':')')"></td><td class="p-2" x-text="courseNumber(c.mark)"></td><td class="p-2" x-text="c.frequency"></td><td class="p-2" x-text="courseNumber(c.percent)"></td><td class="p-2" x-text="c.cumulative"></td></tr></template></tbody></table></div>
    <template x-for="c in courseResult.summary.classes" :key="c.n"><details class="rounded-lg border p-3"><summary class="min-h-11 cursor-pointer font-semibold" x-text="'Bloque '+c.n+' · '+c.frequency+' inmuebles'"></summary><p class="text-sm" x-text="'Media del bloque: '+courseNumber(c.mean)+' COP/m² · CV: '+courseNumber(c.cv)+' % · descripción, no validación de submercado'"></p><template x-for="r in c.members" :key="r.id"><p class="flex flex-wrap items-center gap-3 mt-2"><span x-text="r.label+' · '+courseNumber(r.y)+' COP/m²'"></span><button type="button" class="btn-secondary" @click="await courseReview(r.id)">Revisar inmueble</button></p></template></details></template>
</div></template>
