<details class="mb-3 rounded-xl border p-3">
    <summary class="min-h-11 cursor-pointer font-semibold">Historial estadístico de la depuración</summary>
    <p class="my-2 text-sm">Cada etapa conserva sus cifras y fecha. Reincorporar una muestra agrega otro resultado; no reemplaza el anterior. Las etapas previas a este historial no se reconstruyen.</p>
    <p class="my-2 text-sm">Estadísticos descriptivos sobre oferta / área publicada. En la etapa de factores se calculan sobre filas completas. El valor con descuento usa únicamente descuentos registrados. No son regresión ni valor adoptado; faltan revisar comparabilidad, áreas y componentes.</p>
    <p x-show="!analysisStatistics.some(v=>v.action==='factors')" class="my-2 text-sm">Depuración de factores del analista: pendiente.</p>
    <div class="overflow-auto" tabindex="0" role="region" aria-label="Historial estadístico por etapas"><table class="min-w-full text-left text-sm">
        <thead><tr><?php foreach (['Etapa y fecha','Muestras','Factores aplicados','Filas completas','Base del estadístico','n con valor','Media · COP/m²','Mediana · COP/m²','Desviación · COP/m²','CV · %'] as $heading): ?><th class="p-3"><?= e($heading) ?></th><?php endforeach; ?></tr></thead>
        <tbody><template x-for="(stage,i) in analysisStatistics" :key="i"><tr class="border-t">
            <th class="min-w-48 p-3"><span x-text="({initial:'Información inicial',filter:'Filtro de muestras',restore:'Muestra reincorporada',remove:'Muestra apartada',factors:'Factores del analista'})[stage.action]"></span><p class="font-normal" x-text="new Date(stage.at).toLocaleString('es-CO')"></p><p class="font-normal text-xs" x-show="stage.action!=='initial'" x-text="stage.scope==='all'?'Todas las muestras':'Régimen del sujeto: '+(stage.regime==='si'?'PH':stage.regime==='no'?'No PH':'Sin definir')"></p><p class="break-all font-normal text-xs" x-show="stage.changed" x-text="'Muestra '+(analysisRows.findIndex(r=>r.id===stage.changed)+1)+' · '+(analysisRows.find(r=>r.id===stage.changed)?.source_name || '')"></p></th>
            <td class="p-3" x-text="stage.count"></td><td class="min-w-40 p-3"><span x-text="stage.complete!==null ? (stage.factor_count ?? stage.factors.length+1) : 'Pendiente'"></span><p class="text-xs" x-show="stage.model_area" x-text="'Área del modelo: '+(analysisTable.columns.find(c=>c.key===stage.model_area)?.label || 'Área publicada · m²')"></p><p class="text-xs" x-text="stage.factors.map(k=>analysisTable.columns.find(c=>c.key===k)?.label || 'Factor').join(', ')"></p></td><td class="p-3" x-text="stage.complete ?? 'Pendiente'"></td>
            <td colspan="6" class="p-0"><table class="w-full text-left"><tbody><template x-for="basis in ['offer','adjusted']" :key="basis"><tr><th class="min-w-40 p-3" x-text="basis==='offer'?'Oferta / m²':'Con descuento / m²'"></th><td class="min-w-24 p-3" x-text="stage[basis].n"></td><template x-for="key in ['mean','median','sd','cv']" :key="key"><td class="min-w-36 p-3" x-text="stage[basis][key]===null?'No estimable':new Intl.NumberFormat('es-CO',{maximumFractionDigits:2}).format(stage[basis][key])"></td></template></tr></template></tbody></table></td>
        </tr></template></tbody>
    </table></div>
</details>
