<?php
use App\Support\AppraisalObsolescenceCatalog;
$obs = is_array($obsolescenceProfile ?? null) ? $obsolescenceProfile : AppraisalObsolescenceCatalog::defaults();
$groups = AppraisalObsolescenceCatalog::groups(); $scores = AppraisalObsolescenceCatalog::scores();
$scoreHelp = AppraisalObsolescenceCatalog::scoreHelp(); $metaHelp = AppraisalObsolescenceCatalog::metaHelp();
$factor = static fn (string $g, string $k, string $f): string => (string) ($obs['factors'][$g]['items'][$k][$f] ?? '');
$meta = static fn (string $g): string => (string) ($obs['factors'][$g]['meta'] ?? '');
$short = static function (string $value): string { $value = trim(preg_replace('/\s+/u', ' ', $value) ?? ''); return mb_strlen($value) > 120 ? mb_substr($value, 0, 117) . '…' : $value; };
$levelFromIeo = static fn (float $ieo): string => $ieo == 0.0 ? 'Sin hallazgos' : ($ieo <= 33.33 ? 'Leve' : ($ieo <= 66.67 ? 'Relevante' : 'Crítica'));
$metric = static function (string $groupKey, array $items) use ($factor, $levelFromIeo): array {
    $sum = $applicable = $missingEvidence = 0; $findings = [];
    foreach ($items as $key => $label) {
        $score = $factor($groupKey, (string) $key, 'score'); if ($score === '' || $score === 'na') continue;
        $number = max(0, min(3, (int) $score)); $sum += $number; $applicable++;
        if ($number >= 2 && trim($factor($groupKey, (string) $key, 'evidence')) === '') $missingEvidence++;
        if ($number > 0) $findings[] = (string) $label;
    }
    $ieo = $applicable > 0 ? round(($sum / ($applicable * 3)) * 100, 1) : 0.0;
    return ['ieo'=>$ieo, 'level'=>$levelFromIeo($ieo), 'applicable'=>$applicable, 'sum'=>$sum, 'missing'=>$missingEvidence, 'findings'=>$findings];
};
$metrics = []; foreach ($groups as $groupKey => [, , , , $items]) $metrics[$groupKey] = $metric((string) $groupKey, $items);
$totalSum = array_sum(array_column($metrics, 'sum')); $totalApplicable = array_sum(array_column($metrics, 'applicable'));
$globalIeo = $totalApplicable > 0 ? round(($totalSum / ($totalApplicable * 3)) * 100, 1) : 0.0; $globalLevel = $levelFromIeo($globalIeo);
$activeFindings = []; foreach ($groups as $groupKey => [, $title]) if ($metrics[(string) $groupKey]['findings']) $activeFindings[] = $title . ': ' . implode(', ', array_slice($metrics[(string) $groupKey]['findings'], 0, 4));
$generated = $activeFindings ? 'Obsolescencias: se registran hallazgos de nivel ' . mb_strtolower($globalLevel) . ' con IEO global de ' . number_format($globalIeo, 1, ',', '.') . ' %. ' . implode('; ', $activeFindings) . '. La incidencia económica se define aparte si el hallazgo es material.' : 'Obsolescencias: no se registran hallazgos relevantes con la información revisada. El IEO queda sin hallazgos y no genera descuento automático; cualquier afectación deberá sustentarse de forma separada si se identifica en visita o soporte documental.';
$summary = trim((string) ($obs['summary_text'] ?? '')) ?: $generated;
$pill = static function (string $state): string { return match ($state) { 'ok' => '<span class="rounded-full bg-emerald-100 px-3 py-1 text-xs font-bold text-emerald-800">Completo</span>', 'warn' => '<span class="rounded-full bg-amber-100 px-3 py-1 text-xs font-bold text-amber-800">Revisar</span>', default => '<span class="rounded-full bg-slate-100 px-3 py-1 text-xs font-bold text-slate-700">Opcional</span>' }; };
?>
<form class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm sm:p-8" method="post"
    action="<?= e(url($subjectActionBase . '/obsolescencias')) ?>" data-module-autosave data-save-in-place
    data-autosave-endpoint="<?= e(url($subjectActionBase . '/obsolescencias/autoguardar')) ?>">
    <?= csrf_field() ?>
    <div class="flex flex-wrap items-start justify-between gap-4"><div><p class="eyebrow">3.6 Obsolescencias</p><h2 class="mt-2 text-2xl font-semibold">Diagnóstico técnico de obsolescencias</h2><p class="mt-2 max-w-3xl text-sm leading-6 text-slate-600">Califica cada factor revisado. Si no hay problema, usa “Sin hallazgo”; si no lo revisaste, déjalo “Pendiente”.</p></div><span class="rounded-full bg-blue-100 px-3 py-1 text-xs font-bold text-blue-800">IEO global: <?= e(number_format($globalIeo, 1, ',', '.')) ?> % · <?= e($globalLevel) ?></span></div>
    <div class="mt-5 rounded-xl border border-indigo-100 bg-indigo-50 p-4 text-sm leading-6 text-indigo-950"><h3 class="font-semibold">Academia rápida: cómo se califica y cómo se calcula</h3><div class="mt-3 grid gap-3 lg:grid-cols-5"><p><strong>Pendiente:</strong> no revisado; no entra al IEO.</p><p><strong>0 · Sin hallazgo:</strong> revisado y sin problema.</p><p><strong>1 · Leve:</strong> señal menor.</p><p><strong>2 · Relevante / 3 · Crítica:</strong> hay efecto que debe soportarse.</p><p><strong>N/A:</strong> no corresponde al caso.</p></div><p class="mt-3 rounded-lg bg-white px-3 py-2 text-xs leading-5 text-indigo-900"><strong>Fórmula del bloque:</strong> IEO = (suma de puntajes ÷ número de factores aplicables × 3) × 100. Ejemplo: 5 factores revisados, puntajes 0+0+2+0+1 = 3; máximo 15; IEO = 20 %. La conclusión opcional no puntúa.</p></div>
    <label class="label mt-6 rounded-xl border border-emerald-100 bg-emerald-50 p-4 text-emerald-950">Texto editable para el Entregable<textarea class="input mt-2 min-h-24 bg-white" rows="3" name="summary_text" placeholder="Texto profesional de obsolescencias para incorporar al informe"><?= e($summary) ?></textarea><span class="mt-1 block text-xs font-normal text-emerald-800">El texto se puede dejar corto: diagnóstico, hallazgos relevantes y salvedad de que el IEO no es depreciación automática.</span></label>
    <div class="mt-5 rounded-xl border border-slate-200 bg-white p-4 text-sm leading-6"><h3 class="font-semibold text-slate-900">Matriz de control para construir el Entregable</h3><div class="mt-3 overflow-x-auto"><table class="w-full min-w-[54rem] text-left text-sm"><thead class="text-xs uppercase text-slate-500"><tr><th class="py-2 pr-3">Campo</th><th class="py-2 pr-3">Lectura</th><th class="py-2 pr-3">Estado</th><th class="py-2">Qué hacer</th></tr></thead><tbody class="divide-y divide-slate-100">
        <tr><td class="py-2 pr-3 font-semibold">Texto editable</td><td class="py-2 pr-3">Texto construido</td><td class="py-2 pr-3"><?= $pill('ok') ?></td><td class="py-2 text-slate-600">Listo para ajuste del analista.</td></tr>
        <?php foreach ($groups as $groupKey => [$code, $title]): $m = $metrics[(string) $groupKey]; $state = $m['missing'] > 0 ? 'warn' : ($m['applicable'] > 0 ? 'ok' : 'optional'); ?>
            <tr><td class="py-2 pr-3 font-semibold"><?= e($title) ?></td><td class="py-2 pr-3"><?= e($code . ' · ' . number_format((float) $m['ieo'], 1, ',', '.') . ' % · ' . $m['level']) ?></td><td class="py-2 pr-3"><?= $pill($state) ?></td><td class="py-2 text-slate-600"><?= e($m['missing'] > 0 ? 'Agregar soporte breve en hallazgos relevantes o críticos.' : ($m['applicable'] > 0 ? 'Listo para resumen.' : 'Pendiente; marca sin hallazgo cuando lo revises.')) ?></td></tr>
        <?php endforeach; ?>
        <tr><td class="py-2 pr-3 font-semibold">Cuantificación económica</td><td class="py-2 pr-3"><?= e($short((string) ($obs['quantification_text'] ?? '')) ?: 'Sin efecto económico definido') ?></td><td class="py-2 pr-3"><?= $pill(trim((string) ($obs['quantification_text'] ?? '')) !== '' ? 'ok' : 'warn') ?></td><td class="py-2 text-slate-600">Indicar si no hay efecto material o si se cuantifica aparte.</td></tr>
    </tbody></table></div></div>
    <div class="mt-5 grid gap-4 xl:grid-cols-3">
        <?php foreach ($groups as $groupKey => [$code, $title, $metaLabel, $metaOptions, $items]): $m = $metrics[(string) $groupKey]; $hasFindings = count($m['findings']) > 0; $rawMetaValue = $meta((string) $groupKey); $metaValue = $hasFindings ? $rawMetaValue : ''; $maxScore = $m['applicable'] * 3; $scoreState = []; foreach ($items as $itemKey => $_itemLabel) $scoreState[(string) $itemKey] = $factor((string) $groupKey, (string) $itemKey, 'score'); ?>
            <section class="rounded-xl border border-slate-200 bg-slate-50 p-4" x-data='{scores: <?= e(json_encode($scoreState, JSON_UNESCAPED_UNICODE | JSON_THROW_ON_ERROR)) ?>, value(v) { return ["0", "1", "2", "3"].includes(v) ? Number(v) : null }, applicable() { return Object.values(this.scores).filter(v => this.value(v) !== null).length }, sum() { return Object.values(this.scores).reduce((total, v) => total + (this.value(v) ?? 0), 0) }, max() { return this.applicable() * 3 }, ieo() { return this.max() ? (this.sum() / this.max()) * 100 : 0 }, level() { const ieo = this.ieo(); return ieo === 0 ? "Sin hallazgos" : (ieo <= 33.33 ? "Leve" : (ieo <= 66.67 ? "Relevante" : "Crítica")) }, calcText() { return this.applicable() ? `${this.sum()} / ${this.max()} = ${this.ieo().toFixed(1).replace(".", ",")} %` : "Sin factores revisados; no hay IEO para este bloque." } }'><div class="flex items-start justify-between gap-3"><div><p class="text-xs font-bold text-teal-800"><?= e($code) ?></p><h3 class="mt-1 font-semibold text-slate-900"><?= e($title) ?></h3></div><span class="rounded-full bg-white px-3 py-1 text-xs font-bold text-slate-700" x-text="level()"><?= e($m['level']) ?></span></div><div class="mt-3 rounded-lg border border-blue-100 bg-blue-50 px-3 py-2 text-xs leading-5 text-blue-950"><p><strong>Cómo llenar:</strong> revisa cada fila. Si está bien, selecciona “0 · Sin hallazgo”. Solo escribe soporte cuando haya hallazgo o quieras dejar trazabilidad.</p><p class="mt-1"><strong>Cálculo en vivo:</strong> <span x-text="calcText()"><?= $m['applicable'] > 0 ? e($m['sum'] . ' / ' . $maxScore . ' = ' . number_format((float) $m['ieo'], 1, ',', '.') . ' %') : 'Sin factores revisados; no hay IEO para este bloque.' ?></span></p></div>
                <div class="mt-3 overflow-x-auto rounded-lg border border-slate-200 bg-white"><table class="w-full min-w-[34rem] text-sm"><thead class="bg-slate-100 text-left text-xs uppercase text-slate-500"><tr><th class="p-2">Factor</th><th class="p-2 w-44">Puntaje / estado</th><th class="p-2">Soporte breve</th></tr></thead><tbody class="divide-y divide-slate-100">
                    <?php foreach ($items as $key => $label): $score = $factor((string) $groupKey, (string) $key, 'score'); $warn = in_array($score, ['2','3'], true) && trim($factor((string) $groupKey, (string) $key, 'evidence')) === ''; ?>
                        <tr class="align-top <?= $warn ? 'bg-amber-50' : '' ?>"><td class="p-2 font-semibold text-slate-800"><?= e((string) $label) ?><?php if ($warn): ?><p class="mt-1 text-xs font-semibold text-amber-800">Falta soporte breve.</p><?php endif; ?></td><td class="p-2" x-data='{value: "<?= e($score) ?>", help: <?= e(json_encode($scoreHelp, JSON_UNESCAPED_UNICODE | JSON_THROW_ON_ERROR)) ?>}'><select class="input py-2 text-sm" x-model="value" @change="scores['<?= e((string) $key) ?>'] = value" name="obsolescence[factors][<?= e((string) $groupKey) ?>][items][<?= e((string) $key) ?>][score]"><option value="">Pendiente</option><?php foreach ($scores as $value => $labelScore): ?><option value="<?= e((string) $value) ?>" <?= $score === (string) $value ? 'selected' : '' ?>><?= e((string) $labelScore) ?></option><?php endforeach; ?></select><p class="mt-1 text-[11px] leading-4 text-slate-600" x-text="help[value] || help['']"></p></td><td class="p-2"><textarea class="input min-h-12 py-2 text-sm" rows="2" name="obsolescence[factors][<?= e((string) $groupKey) ?>][items][<?= e((string) $key) ?>][evidence]" placeholder="Opcional si está sin hallazgo. Obligatorio si es relevante o crítica."><?= e($factor((string) $groupKey, (string) $key, 'evidence')) ?></textarea></td></tr>
                    <?php endforeach; ?>
                </tbody></table></div>
                <label class="label mt-3 rounded-lg border border-amber-100 bg-amber-50 p-3 text-sm text-amber-950" x-data='{value: "<?= e($metaValue) ?>", help: <?= e(json_encode($metaHelp, JSON_UNESCAPED_UNICODE | JSON_THROW_ON_ERROR)) ?>}'>Conclusión opcional del bloque: <?= e($metaLabel) ?><select class="input mt-1 py-2 text-sm" x-model="value" name="obsolescence[factors][<?= e((string) $groupKey) ?>][meta]"><option value="">Sin conclusión general</option><?php foreach ($metaOptions as $value => $label): ?><option value="<?= e((string) $value) ?>" <?= $metaValue === (string) $value ? 'selected' : '' ?>><?= e((string) $label) ?></option><?php endforeach; ?></select><span class="mt-1 block rounded-lg bg-white px-3 py-2 text-xs font-normal leading-5" x-text="help[value] || help['']"></span><?php if (!$hasFindings): ?><span class="mt-2 block text-xs font-semibold">No hay factores con hallazgo; esta conclusión se guardará como “Sin conclusión general”.</span><?php endif; ?></label>
            </section>
        <?php endforeach; ?>
    </div>
    <div class="mt-5 grid gap-4 lg:grid-cols-3"><label class="label">Diagnóstico técnico<textarea class="input min-h-20" rows="3" name="diagnosis_text" placeholder="Conclusión breve: qué se observó y qué no se evidenció"><?= e((string) ($obs['diagnosis_text'] ?? '')) ?></textarea></label><label class="label">Incidencia económica<textarea class="input min-h-20" rows="3" name="quantification_text" placeholder="Sin efecto material, pendiente de cuantificar o criterio usado si aplica"><?= e((string) ($obs['quantification_text'] ?? '')) ?></textarea></label><label class="label">Fundamento técnico<textarea class="input min-h-20" rows="3" name="normative_text" placeholder="IVS, IGAC, NTS, visita, mercado o salvedad aplicable"><?= e((string) ($obs['normative_text'] ?? '')) ?></textarea></label></div>
    <div class="mt-5 rounded-xl border border-blue-100 bg-blue-50 p-4 text-sm leading-6 text-blue-950"><strong>Regla práctica:</strong> si todo está bien, marca los factores revisados como “Sin hallazgo” y deja la conclusión opcional en “Sin conclusión general”.</div>
    <div class="mt-6 flex justify-end"><button class="btn-primary" type="submit">Guardar obsolescencias</button></div>
</form>