<?php
$m = $metrics[(string) $groupKey];
$hasFindings = count($m['findings']) > 0;
$rawMetaValue = $meta((string) $groupKey);
$metaValue = $hasFindings ? $rawMetaValue : '';
$guide = $readerGuidance[$groupKey];
?>
        <section class="mt-5 rounded-xl border border-slate-200 bg-slate-50 p-4" x-show="activeObs === '<?= e((string) $groupKey) ?>'">
            <div class="flex items-start justify-between gap-3"><div><p class="text-xs font-bold text-teal-800"><?= e($code) ?></p><h3 class="mt-1 text-xl font-semibold text-slate-900"><?= e($title) ?></h3></div><span class="rounded-full bg-white px-3 py-1 text-xs font-bold text-slate-700" x-text="groupLevel('<?= e((string) $groupKey) ?>')"><?= e($m['level']) ?></span></div>
            <div class="mt-3 grid gap-3 lg:grid-cols-3"><p class="rounded-lg bg-white p-3 text-xs leading-5 text-slate-700"><strong>Qué significa:</strong> <?= e($guide['definition']) ?></p><p class="rounded-lg bg-white p-3 text-xs leading-5 text-slate-700"><strong>Si está bien:</strong> <?= e($guide['no_finding']) ?></p><p class="rounded-lg bg-white p-3 text-xs leading-5 text-slate-700"><strong>Cómo se sustenta:</strong> <?= e($guide['support']) ?></p></div>
            <div class="mt-3 rounded-lg border border-blue-100 bg-blue-50 px-3 py-2 text-xs leading-5 text-blue-950"><p><strong>Lectura del bloque:</strong> <span x-text="groupCalc('<?= e((string) $groupKey) ?>')"></span>. La conclusión opcional describe el hallazgo predominante; no es una medición normativa ni cambia la incidencia económica por sí sola.</p></div>
            <div class="mt-3 overflow-x-auto rounded-lg border border-slate-200 bg-white"><table class="w-full min-w-[58rem] text-sm"><thead class="bg-slate-100 text-left text-xs uppercase text-slate-500"><tr><th class="p-2">Factor y contexto</th><th class="p-2 w-56">Lectura del factor</th><th class="p-2">Soporte breve</th></tr></thead><tbody class="divide-y divide-slate-100">
                <?php foreach ($items as $key => $label): $score = $factor((string) $groupKey, (string) $key, 'score'); $evidence = $factor((string) $groupKey, (string) $key, 'evidence'); $warn = in_array($score, ['2','3'], true) && trim($evidence) === ''; ?>
                    <tr class="align-top" x-data='{group: "<?= e((string) $groupKey) ?>", item: "<?= e((string) $key) ?>"}' :class="needsSupport(group, item) ? 'bg-amber-50' : ''"><td class="p-2"><p class="font-semibold text-slate-900"><?= e((string) $label) ?></p><p class="mt-1 text-xs leading-5 text-slate-600"><?= e((string) ($factorHelp[$groupKey][$key] ?? 'Revise este factor según la tipología y el alcance del avalúo.')) ?></p><p class="mt-1 text-xs font-semibold text-amber-800" x-show="needsSupport(group, item)" x-cloak>Falta soporte breve.</p></td><td class="p-2"><select class="input py-2 text-sm" x-model="allScores[group][item]" name="obsolescence[factors][<?= e((string) $groupKey) ?>][items][<?= e((string) $key) ?>][score]"><option value="">Pendiente</option><?php foreach ($scores as $value => $labelScore): ?><option value="<?= e((string) $value) ?>" <?= $score === (string) $value ? 'selected' : '' ?>><?= e((string) $labelScore) ?></option><?php endforeach; ?></select><p class="mt-1 text-[11px] leading-4 text-slate-600" x-text="scoreText(group, item)"></p></td><td class="p-2"><textarea class="input min-h-16 py-2 text-sm" rows="3" x-model="allEvidence[group][item]" name="obsolescence[factors][<?= e((string) $groupKey) ?>][items][<?= e((string) $key) ?>][evidence]" placeholder="Si está sin hallazgo, puede dejar una nota corta. Si es relevante o crítica, escriba soporte claro."><?= e($evidence) ?></textarea></td></tr>
                <?php endforeach; ?>
            </tbody></table></div>
            <label class="label mt-3 rounded-lg border border-amber-100 bg-amber-50 p-3 text-sm text-amber-950" x-data='{value: "<?= e($metaValue) ?>", help: <?= e(json_encode($metaHelp, JSON_UNESCAPED_UNICODE | JSON_THROW_ON_ERROR)) ?>}'>Conclusión opcional del bloque: <?= e($metaLabel) ?><select class="input mt-1 py-2 text-sm" x-model="value" name="obsolescence[factors][<?= e((string) $groupKey) ?>][meta]"><option value="">Sin conclusión general</option><?php foreach ($metaOptions as $value => $label): ?><option value="<?= e((string) $value) ?>" <?= $metaValue === (string) $value ? 'selected' : '' ?>><?= e((string) $label) ?></option><?php endforeach; ?></select><span class="mt-1 block rounded-lg bg-white px-3 py-2 text-xs font-normal leading-5" x-text="help[value] || help['']"></span><?php if (!$hasFindings): ?><span class="mt-2 block text-xs font-semibold">No hay factores con hallazgo; esta conclusión se guardará como “Sin conclusión general”.</span><?php endif; ?></label>
        </section>
