<?php
$urbanIndexTip = static fn (string $text): string => '<span class="help-dot" title="' . e($text) . '">?</span>';
?>
        <div x-show="usePane === 'indices'" class="mt-6 grid gap-4 rounded-xl border border-amber-100 bg-amber-50 p-4">
            <div class="grid gap-4 lg:grid-cols-[1fr_1.1fr]">
                <div><h3 class="font-semibold text-amber-950">Índices y áreas</h3><p class="mt-1 text-sm leading-6 text-amber-900">Aquí se organiza lo básico para saber si la norma solo se anexa al avalúo o si puede cambiar el enfoque del análisis. No reemplaza diseño arquitectónico, cabida ni licencia.</p></div>
                <div class="rounded-xl border border-amber-200 bg-white p-4 text-sm leading-6 text-amber-950">
                    <p class="font-semibold">Academia rápida: ¿de dónde saco los datos?</p>
                    <ul class="mt-2 list-disc space-y-1 pl-5">
                        <li><strong>Terreno:</strong> escritura, certificado catastral, predial, MIDAS, plano o medición adoptada en 3.2.</li>
                        <li><strong>Construido actual:</strong> visita, medición, planos, licencia, catastro o ficha predial; si hay diferencias, explique la fuente adoptada.</li>
                        <li><strong>Retiros, afectaciones o cesiones:</strong> POT, ficha normativa, licencia, plan parcial, riesgo, rondas, vías, servidumbres o concepto oficial.</li>
                        <li><strong>Índices y altura:</strong> cuadro POT, norma urbana, licencia vigente o concepto de planeación. Si la norma usa una fórmula distinta, escríbala y no fuerce el índice.</li>
                        <li><strong>Potencial:</strong> área máxima construible menos área construida actual. Sirve para orientar mayor y mejor uso y método residual; no es valor definitivo.</li>
                    </ul>
                </div>
            </div>
            <div class="grid gap-4 rounded-xl border border-sky-100 bg-white p-4 md:grid-cols-3">
                <label class="label">Modalidad residencial a probar <?= $urbanIndexTip('Escoge la subopción del Cuadro No. 1 que quieres verificar. No es lo mismo vivienda unifamiliar, bifamiliar o multifamiliar: cada una tiene área mínima, frente e índice propio.') ?><select class="input" name="normative_modality" x-model="modality">
                    <option value="">Selecciona si aplica</option>
                    <?php foreach ($residentialModeOptions as $key => $label): ?><option value="<?= e($key) ?>" <?= e($selected('normative_modality', (string) $key)) ?>><?= e($label) ?></option><?php endforeach; ?>
                </select></label>
                <label class="label">Frente del lote m <?= $urbanIndexTip('Dato conectado con 3.2. Si está vacío, complétalo en Bien sujeto > superficies; aquí queda bloqueado para no duplicar fuentes.') ?><input class="input bg-slate-50" type="text" name="lot_front_normative_m" x-model="front" readonly value="<?= e($value('lot_front_normative_m')) ?>" placeholder="Viene de 3.2"></label>
                <div class="rounded-xl border border-sky-100 bg-sky-50 p-3 text-sm leading-6 text-sky-950">
                    <p class="font-semibold">Chequeo básico según cuadro</p>
                    <p class="whitespace-pre-line" x-text="compliance()"></p>
                    <button class="btn-secondary mt-3" type="button" @click="applyReq()">Usar índice de esta modalidad</button>
                </div>
                <label class="label md:col-span-3">Resumen de cumplimiento área/frente/índice <?= $urbanIndexTip('Guarda aquí la lectura que luego explica por qué una modalidad se adopta o se descarta. Ejemplo: para multifamiliar RD no cumple frente mínimo 25 m si el predio tiene 12 m.') ?><textarea class="input min-h-24" name="normative_compliance_summary" rows="3" maxlength="5000" x-model="complianceSummary" placeholder="Se puede llenar con el botón o escribir criterio del perito."></textarea></label>
            </div>
            <div class="grid gap-4 md:grid-cols-4">
                <label class="label">Área del terreno m² <?= $urbanIndexTip('Dato conectado con el área adoptada de 3.2. Si no aparece, corrige el área del terreno en el módulo 3; aquí no se edita para conservar trazabilidad.') ?><input class="input bg-slate-50" type="text" name="land_area_normative_m2" x-model="land" readonly value="<?= e($value('land_area_normative_m2')) ?>" placeholder="Viene de 3.2"></label>
                <label class="label">Retiros / afectaciones % <?= $urbanIndexTip('Registra la porción del terreno que no se puede aprovechar por retiro, cesión, ronda, vía, servidumbre, riesgo o afectación. Si no aplica, deja 0.') ?><input class="input" type="text" name="setback_area_percent" x-model="affect" inputmode="decimal" maxlength="40" value="<?= e($value('setback_area_percent')) ?>" placeholder="Ej. 40 o 0,40"></label>
                <label class="label">Área neta normativa m² <?= $urbanIndexTip('Es el terreno útil después de descontar restricciones. Puede venir de la norma o se puede estimar con el porcentaje de afectación cuando solo se requiere orientación.') ?><input class="input bg-white" type="text" name="net_land_area_m2" x-model="net" :placeholder="fmt(netArea()) || 'Ej. 222'" inputmode="decimal" maxlength="40" value="<?= e($value('net_land_area_m2')) ?>"></label>
                <label class="label">Índice de ocupación <?= $urbanIndexTip('Porcentaje o factor del lote que puede ocupar la huella del edificio en primer piso. Sale del cuadro normativo, licencia o concepto oficial.') ?><input class="input" type="text" name="occupancy_index" x-model="occ" inputmode="decimal" maxlength="40" value="<?= e($value('occupancy_index')) ?>" placeholder="Ej. 0,60"></label>
                <label class="label">Altura máxima pisos <?= $urbanIndexTip('Número de pisos o altura permitida por la norma. Si depende de frente, vía, tratamiento o cesiones, anota la condición en restricciones.') ?><input class="input" type="text" name="max_floors" x-model="floors" inputmode="decimal" maxlength="40" value="<?= e($value('max_floors')) ?>" placeholder="Ej. 2"></label>
                <label class="label">Índice de construcción <?= $urbanIndexTip('Factor total de construcción permitido. Si la norma no lo trae explícito, puede aproximarse como ocupación por pisos, siempre dejando observación.') ?><input class="input" type="text" name="construction_index" x-model="ci" inputmode="decimal" maxlength="40" value="<?= e($value('construction_index')) ?>" placeholder="Opcional; vacío usa ocupación × pisos"></label>
                <label class="label">Construcción proyectada m² <?= $urbanIndexTip('Área máxima construible estimada con área neta e índice normativo. Es una proyección básica para orientar potencial; si tienes cabida o concepto, puedes adoptarla revisando la conclusión.') ?><input class="input bg-slate-50" type="text" name="normative_max_built_area_m2" :value="fmt(maxBuild()) || maxBuilt" readonly placeholder="Se calcula con norma"></label>
                <label class="label">Factor área vendible <?= $urbanIndexTip('Relación preliminar entre área construible y área vendible. Úsalo solo como orientación para residual; depende de producto, circulación, parqueaderos y diseño.') ?><input class="input" type="text" name="sellable_area_factor" x-model="sellFactor" inputmode="decimal" maxlength="40" value="<?= e($value('sellable_area_factor')) ?>" placeholder="Ej. 0,75 o 1,20"></label>
                <label class="label md:col-span-2">Área vendible ref. m² <?= $urbanIndexTip('Estimación de área vendible que puede alimentar más adelante el capítulo de valoración. Si no hay soporte, déjala como referencia o pendiente.') ?><input class="input bg-white" type="text" name="sellable_area_m2" x-model="sellable" :placeholder="fmt(sellableArea()) || 'Solo si aplica'" inputmode="decimal" maxlength="40" value="<?= e($value('sellable_area_m2')) ?>"></label>
                <label class="label">Construcción actual m² <?= $urbanIndexTip('Dato conectado con la construcción adoptada de 3.3/MIDAS/catastro. Si está vacío, complétalo en Bien sujeto; aquí queda bloqueado para no volver a buscar información.') ?><input class="input bg-slate-50" type="text" name="actual_built_area_m2" x-model="actual" readonly value="<?= e($value('actual_built_area_m2')) ?>" placeholder="Viene de módulo 3"></label>
                <label class="label">Potencial adicional m² <?= $urbanIndexTip('Construcción proyectada menos construcción actual. Si es positivo, hay indicio de potencial; si es cero, negativo o condicionado, explícalo.') ?><input class="input bg-slate-50" type="text" name="buildable_difference_m2" :value="fmt(potential()) || '<?= e($value('buildable_difference_m2')) ?>'" readonly placeholder="Proyectada - actual"></label>
                <label class="label md:col-span-4">Frente, fondo, forma, topografía o restricción que afecte el cálculo <?= $urbanIndexTip('Use este campo para explicar lo que puede limitar el número: frente insuficiente, forma irregular, pendiente, servidumbre, afectación, retiro, cesión, redes, riesgo o acceso.') ?><textarea class="input min-h-24" name="norm_physical_base_text" rows="3" maxlength="5000" placeholder="Solo lo que incide: frente insuficiente, forma irregular, pendiente, servidumbre, cesión, afectación o restricción."><?= e($value('norm_physical_base_text')) ?></textarea></label>
            </div>
        </div>
        <div x-show="usePane === 'potencial'" class="mt-6 grid gap-4 rounded-xl border border-blue-100 bg-blue-50 p-4">
            <div class="grid gap-4 lg:grid-cols-[1fr_1.1fr]"><div><h3 class="font-semibold text-blue-950">Criterio pericial del potencial</h3><p class="mt-1 text-sm leading-6 text-blue-900">Aquí no se califica un proyecto. El perito solo deja si la norma sustenta potencial adicional, si está condicionado o si se anexa únicamente como soporte NTS.</p></div><div class="rounded-xl border border-blue-200 bg-white p-4 text-sm leading-6 text-blue-950"><p class="font-semibold">Cómo leerlo</p><p class="mt-1">Compare norma contra terreno, frente y construcción actual. Si faltan soportes o el predio no cumple una condición mínima, no adopte potencial adicional; deje la norma y la salvedad para el informe.</p></div></div>
            <label class="label">Conclusión valuatoria del potencial normativo <?= $urbanIndexTip('Seleccione el criterio del avalúo, no la viabilidad de un proyecto. Sirve para decidir si el potencial se adopta, queda condicionado o solo se deja como soporte normativo.') ?><select class="input" name="constructive_potential_status">
                <?php foreach ([''=>'Selecciona conclusión si aplica','viable'=>'Indicio de potencial normativo','limitado'=>'Potencial condicionado por área, frente o restricción','no_viable'=>'No se adopta potencial adicional con la información disponible','requiere_arquitecto'=>'Pendiente de cabida o soporte técnico para adoptar potencial','requiere_concepto'=>'Pendiente de concepto oficial'] as $key => $label): ?><option value="<?= e($key) ?>" <?= e($selected('constructive_potential_status', (string) $key)) ?>><?= e($label) ?></option><?php endforeach; ?>
            </select></label>
            <div class="grid gap-4 md:grid-cols-2">
                <?php $textarea('norm_max_height_text', 'Altura o pisos permitidos', 'Pisos, altura o condición aplicable.', 3, 70000); ?>
                <?php $textarea('norm_construction_index_text', 'Índice, ocupación o área construible', 'Índice, ocupación, área vendible preliminar o fórmula.', 3, 70000); ?>
                <?php $textarea('norm_free_area_text', 'Área libre, aislamientos y retiros', 'Área libre, antejardín, retiro lateral/posterior y restricciones físicas.', 3, 70000); ?>
                <?php $textarea('norm_min_lot_front_text', 'Área y frente mínimos', 'AML, frente mínimo y regla de lote.', 3, 70000); ?>
                <div class="md:col-span-2"><?php $textarea('constructive_potential_notes', 'Conclusión pericial del potencial', 'Ej. la norma permite mayor área que la existente, pero se adopta o descarta según frente, área mínima, restricciones y soporte revisado.', 4); ?></div>
                <div class="md:col-span-2"><?php $textarea('norm_other_potential_text', 'Otros parámetros útiles', 'Parqueaderos, cesiones, usos mixtos, servicios, tiempos y riesgos. Mezanines o balcones requieren validación técnica.', 4, 70000); ?></div>
            </div>
        </div>
