<?php
$urbanIndexTip = static fn (string $text): string => '<span class="help-dot" title="' . e($text) . '">?</span>';
?>
        <div x-show="usePane === 'indices'" class="mt-6 grid gap-4 rounded-xl border border-amber-100 bg-amber-50 p-4">
            <div class="grid gap-4 lg:grid-cols-[1fr_1.1fr]">
                <div><h3 class="font-semibold text-amber-950">Índices y áreas</h3><p class="mt-1 text-sm leading-6 text-amber-900">Aquí se organiza lo básico para saber si la norma solo se anexa al avalúo o si puede cambiar el enfoque del análisis. No reemplaza diseño arquitectónico, cabida ni licencia.</p></div>
                <div class="rounded-xl border border-amber-200 bg-white p-4 text-sm leading-6 text-amber-950">
                    <p class="font-semibold">Academia rápida: ¿de dónde saco los datos?</p>
                    <ul class="mt-2 list-disc space-y-1 pl-5">
                        <li><strong>Terreno:</strong> escritura, certificado catastral, predial, MIDAS, plano o medición adoptada en 3.2.</li>
                        <li><strong>Construido actual:</strong> visita, medición, planos, licencia, catastro o ficha predial; si hay diferencias, explique la fuente adoptada.</li>
                        <li><strong>Retiros, afectaciones o cesiones:</strong> POT, ficha normativa, licencia, plan parcial, riesgo, rondas, vías, servidumbres o concepto oficial.</li>
                        <li><strong>Índices y altura:</strong> cuadro POT, norma urbana, licencia vigente o concepto de planeación. Si la norma usa una fórmula distinta, escríbala y no fuerce el índice.</li>
                        <li><strong>Potencial:</strong> área máxima construible menos área construida actual. Sirve para orientar mayor y mejor uso y método residual; no es valor definitivo.</li>
                    </ul>
                </div>
            </div>
            <div class="grid gap-4 md:grid-cols-4">
                <label class="label">Área del terreno m² <?= $urbanIndexTip('Tómala de escritura, certificado catastral, factura predial, MIDAS, plano o del área adoptada en 3.2. Si las fuentes no coinciden, usa la más sustentable y deja la salvedad.') ?><input class="input" type="text" name="land_area_normative_m2" x-model="land" inputmode="decimal" maxlength="40" value="<?= e($value('land_area_normative_m2')) ?>" placeholder="Ej. 370"></label>
                <label class="label">Retiros / afectaciones % <?= $urbanIndexTip('Registra la porción del terreno que no se puede aprovechar por retiro, cesión, ronda, vía, servidumbre, riesgo o afectación. Si no aplica, deja 0.') ?><input class="input" type="text" name="setback_area_percent" x-model="affect" inputmode="decimal" maxlength="40" value="<?= e($value('setback_area_percent')) ?>" placeholder="Ej. 40 o 0,40"></label>
                <label class="label">Área neta normativa m² <?= $urbanIndexTip('Es el terreno útil después de descontar restricciones. Puede venir de la norma o se puede estimar con el porcentaje de afectación cuando solo se requiere orientación.') ?><input class="input bg-white" type="text" name="net_land_area_m2" x-model="net" :placeholder="fmt(netArea()) || 'Ej. 222'" inputmode="decimal" maxlength="40" value="<?= e($value('net_land_area_m2')) ?>"></label>
                <label class="label">Índice de ocupación <?= $urbanIndexTip('Porcentaje o factor del lote que puede ocupar la huella del edificio en primer piso. Sale del cuadro normativo, licencia o concepto oficial.') ?><input class="input" type="text" name="occupancy_index" x-model="occ" inputmode="decimal" maxlength="40" value="<?= e($value('occupancy_index')) ?>" placeholder="Ej. 0,60"></label>
                <label class="label">Altura máxima pisos <?= $urbanIndexTip('Número de pisos o altura permitida por la norma. Si depende de frente, vía, tratamiento o cesiones, anota la condición en restricciones.') ?><input class="input" type="text" name="max_floors" x-model="floors" inputmode="decimal" maxlength="40" value="<?= e($value('max_floors')) ?>" placeholder="Ej. 2"></label>
                <label class="label">Índice de construcción <?= $urbanIndexTip('Factor total de construcción permitido. Si la norma no lo trae explícito, puede aproximarse como ocupación por pisos, siempre dejando observación.') ?><input class="input" type="text" name="construction_index" x-model="ci" inputmode="decimal" maxlength="40" value="<?= e($value('construction_index')) ?>" placeholder="Opcional; vacío usa ocupación × pisos"></label>
                <label class="label">Área máxima construible m² <?= $urbanIndexTip('Área teórica permitida por la norma. Si el campo queda vacío, se orienta con área neta por índice de construcción. Revísala antes de adoptar.') ?><input class="input bg-white" type="text" name="normative_max_built_area_m2" x-model="maxBuilt" :placeholder="fmt(maxBuild()) || 'Ej. 300'" inputmode="decimal" maxlength="40" value="<?= e($value('normative_max_built_area_m2')) ?>"></label>
                <label class="label">Factor área vendible <?= $urbanIndexTip('Relación preliminar entre área construible y área vendible. Úsalo solo como orientación para residual; depende de producto, circulación, parqueaderos y diseño.') ?><input class="input" type="text" name="sellable_area_factor" x-model="sellFactor" inputmode="decimal" maxlength="40" value="<?= e($value('sellable_area_factor')) ?>" placeholder="Ej. 0,75 o 1,20"></label>
                <label class="label md:col-span-2">Área vendible ref. m² <?= $urbanIndexTip('Estimación de área vendible que puede alimentar más adelante el capítulo de valoración. Si no hay soporte, déjala como referencia o pendiente.') ?><input class="input bg-white" type="text" name="sellable_area_m2" x-model="sellable" :placeholder="fmt(sellableArea()) || 'Solo si aplica'" inputmode="decimal" maxlength="40" value="<?= e($value('sellable_area_m2')) ?>"></label>
                <label class="label">Área construida actual m² <?= $urbanIndexTip('Área existente adoptada del inmueble. Para una casa puede venir de visita, medición, planos o catastro; para PH normalmente se toma de documentos de propiedad.') ?><input class="input" type="text" name="actual_built_area_m2" x-model="actual" inputmode="decimal" maxlength="40" value="<?= e($value('actual_built_area_m2')) ?>" placeholder="Ej. 230"></label>
                <label class="label">Potencial adicional m² <?= $urbanIndexTip('Diferencia entre lo máximo normativo y lo construido actual. Si es positivo, hay indicio de potencial; si es cero, negativo o condicionado, explique por qué.') ?><input class="input bg-white" type="text" name="buildable_difference_m2" :value="fmt(potential()) || '<?= e($value('buildable_difference_m2')) ?>'" inputmode="decimal" maxlength="40" placeholder="Norma vs existente"></label>
                <label class="label md:col-span-4">Frente, fondo, forma, topografía o restricción que afecte el cálculo <?= $urbanIndexTip('Use este campo para explicar lo que puede limitar el número: frente insuficiente, forma irregular, pendiente, servidumbre, afectación, retiro, cesión, redes, riesgo o acceso.') ?><textarea class="input min-h-24" name="norm_physical_base_text" rows="3" maxlength="5000" placeholder="Solo lo que incide: frente insuficiente, forma irregular, pendiente, servidumbre, cesión, afectación o restricción."><?= e($value('norm_physical_base_text')) ?></textarea></label>
            </div>
        </div>
        <div x-show="usePane === 'potencial'" class="mt-6 grid gap-4 rounded-xl border border-blue-100 bg-blue-50 p-4">
            <div class="grid gap-4 lg:grid-cols-[1fr_1.1fr]"><div><h3 class="font-semibold text-blue-950">Lectura del potencial</h3><p class="mt-1 text-sm leading-6 text-blue-900">Aquí el perito convierte los números en criterio: si el inmueble tiene potencial, si está limitado o si solo se deja la norma como soporte NTS.</p></div><div class="rounded-xl border border-blue-200 bg-white p-4 text-sm leading-6 text-blue-950"><p class="font-semibold">Cómo leerlo</p><p class="mt-1">En casa o lote, compare norma contra construcción actual y mercado. En PH normalmente la norma soporta el informe, pero el potencial individual suele ser limitado. Si el dato exige diseño, cargas, parqueaderos, aislamientos complejos o cabida, marque que requiere arquitecto o concepto oficial.</p></div></div>
            <label class="label">Estado pericial del potencial <?= $urbanIndexTip('Seleccione la conclusión técnica: viable, limitado, no viable o pendiente de soporte especializado. Este estado orienta el entregable y el capítulo de valoración.') ?><select class="input" name="constructive_potential_status">
                <?php foreach ([''=>'Selecciona estado si aplica','viable'=>'Viable con soporte básico','limitado'=>'Limitado o condicionado','no_viable'=>'No viable / sin potencial individual','requiere_arquitecto'=>'Requiere arquitecto o cabida','requiere_concepto'=>'Requiere concepto oficial'] as $key => $label): ?><option value="<?= e($key) ?>" <?= e($selected('constructive_potential_status', (string) $key)) ?>><?= e($label) ?></option><?php endforeach; ?>
            </select></label>
            <div class="grid gap-4 md:grid-cols-2">
                <?php $textarea('norm_max_height_text', 'Altura o pisos permitidos', 'Pisos, altura o condición aplicable.', 3, 70000); ?>
                <?php $textarea('norm_construction_index_text', 'Índice, ocupación o área construible', 'Índice, ocupación, área vendible preliminar o fórmula.', 3, 70000); ?>
                <?php $textarea('norm_free_area_text', 'Área libre, aislamientos y retiros', 'Área libre, antejardín, retiro lateral/posterior y restricciones físicas.', 3, 70000); ?>
                <?php $textarea('norm_min_lot_front_text', 'Área y frente mínimos', 'AML, frente mínimo y regla de lote.', 3, 70000); ?>
                <div class="md:col-span-2"><?php $textarea('constructive_potential_notes', 'Conclusión del potencial', 'Ej. potencial adicional aproximado; se analiza si es legal, viable y relevante. O: PH sin potencial individual verificable.', 4); ?></div>
                <div class="md:col-span-2"><?php $textarea('norm_other_potential_text', 'Otros parámetros útiles', 'Parqueaderos, cesiones, usos mixtos, servicios, tiempos y riesgos. Mezanines o balcones requieren validación técnica.', 4, 70000); ?></div>
            </div>
        </div>
