import Alpine from 'alpinejs';
import { appraisalForm } from './appraisal-form.js';
import { installFetchNavigation } from './fetch-navigation.js';
import { installModuleAutosave } from './module-autosave.js';
import { photoUpload } from './photo-upload.js';
import { sectorBankTabs } from './sector-bank-tabs.js';
import { subjectAttributes } from './subject-attributes.js';
import { installPhPdfUpload } from './ph-pdf-upload.js';
import { phCommonLive } from './ph-common-live.js';
import { obsolescenceLive } from './obsolescence-live.js';
import { installUploadProgress } from './upload-progress.js';
import { installHelpTooltips } from './help-tooltips.js';
import { installConservationSummaryLive } from './conservation-summary-live.js';
import { installMoneyInputs } from './money-input.js';
import { installDerivedRefresh } from './derived-refresh.js';
import { installComparableBulkImport } from './comparable-bulk-import.js';
import { comparableWorkbench } from './comparable-workbench.js';
import { installComparableUrlImport } from './comparable-url-import.js';
import { fincaraizAreaSearch } from './fincaraiz-area-search.js';
import { ciencuadrasPaste } from './ciencuadras-paste.js';
import { properatiPaste } from './properati-paste.js';

window.Alpine = Alpine;
Alpine.data('ciencuadrasPaste', ciencuadrasPaste);
Alpine.data('properatiPaste', properatiPaste);
Alpine.data('fincaraizAreaSearch', fincaraizAreaSearch);
Alpine.data('comparableWorkbench', comparableWorkbench);
Alpine.data('appraisalForm', appraisalForm);
Alpine.data('photoUpload', photoUpload);
Alpine.data('sectorBankTabs', sectorBankTabs);
Alpine.data('subjectAttributes', subjectAttributes);
Alpine.data('phCommonLive', phCommonLive);
Alpine.data('obsolescenceLive', obsolescenceLive);
Alpine.start();
installModuleAutosave();
installPhPdfUpload();
installUploadProgress();
installHelpTooltips();
installConservationSummaryLive();
installMoneyInputs();
installDerivedRefresh();
installComparableBulkImport();
installComparableUrlImport();
installFetchNavigation();
