import Alpine from 'alpinejs';
import { appraisalForm } from './appraisal-form.js';
import { installFetchNavigation } from './fetch-navigation.js';
import { installModuleAutosave } from './module-autosave.js';
import { photoUpload } from './photo-upload.js';
import { sectorBankTabs } from './sector-bank-tabs.js';
import { subjectAttributes } from './subject-attributes.js';
import { installPhPdfUpload } from './ph-pdf-upload.js';
import { phCommonLive } from './ph-common-live.js';
import { obsolescenceLive } from './obsolescence-live.js';
import { installUploadProgress } from './upload-progress.js';

window.Alpine = Alpine;
Alpine.data('appraisalForm', appraisalForm);
Alpine.data('photoUpload', photoUpload);
Alpine.data('sectorBankTabs', sectorBankTabs);
Alpine.data('subjectAttributes', subjectAttributes);
Alpine.data('phCommonLive', phCommonLive);
Alpine.data('obsolescenceLive', obsolescenceLive);
Alpine.start();
installModuleAutosave();
installPhPdfUpload();
installUploadProgress();
installFetchNavigation();
