<?php
declare(strict_types=1);
(static function():void {
    $post=['label'=>'Jacuzzi verificado de prueba','why'=>'Presencia comprobada en la unidad','unit'=>'sí/no','kind'=>'binary','categories'=>'No / Sí','group'=>'Unidad privada','types'=>['apartamento','casa']];
    $data=\App\Services\UserResearchFactorInput::input($post);
    expect($data['categories']==="No\nSí" && $data['types']===['apartamento','casa'],'nuevo binario conserva ausencia cero y presencia uno para todos sus tipos');
    expectStatus(422,fn()=>\App\Services\UserResearchFactorInput::input(array_replace($post,['types'=>['inventado']])),'no admite asignar factor a tipo inexistente');
    expectStatus(422,fn()=>\App\Services\UserResearchFactorInput::input(array_replace($post,['label'=>'Baños'])),'nombre repetido orienta a editar el existente');
    expectStatus(422,fn()=>\App\Services\UserResearchFactorInput::input(array_replace($post,['kind'=>'ordinal','categories'=>"No\nPendiente\nSí"])),'desconocido no se convierte en un nivel de jerarquía');
    expectStatus(422,fn()=>\App\Services\UserResearchFactorInput::input(array_replace($post,['kind'=>'ordinal','categories'=>"No\nno"])),'rechaza niveles repetidos aunque cambien mayúsculas');
    expectStatus(422,fn()=>\App\Services\UserResearchFactorInput::input($post,'area'),'bases de cálculo no se redefinen como atributos');
    $base=\App\Services\ResearchFactorCatalog::all()['age'];
    expectStatus(422,fn()=>\App\Services\UserResearchFactorInput::input(array_replace($post,['label'=>'Edad','unit'=>'meses','kind'=>'numeric']),'age'),'no cambia años por meses sobre calificaciones previas');
    $office=\App\Services\ResearchFactorCatalog::forType('oficina');
    expect(count(array_diff_key($office,array_flip(['area','destination'])))===13 && $office['corner']['group']==='Unidad privada','oficina queda con trece atributos aprobados y esquina privada');
    $old=['unit_kind'=>'property','property_type'=>'oficina','subject_factors_json'=>json_encode(['air_conditioning'=>['value'=>'Sí']])];
    expect(isset(\App\Services\SubjectFactorCapture::catalog($old,[])['air_conditioning']),'retirar aire acondicionado no elimina captura histórica del sujeto');
    $finish=\App\Services\ResearchFactorCatalog::all()['finish_quality'];
    $warehouse=\App\Services\SubjectFactorCapture::catalog(['unit_kind'=>'property','property_type'=>'bodega'],[]);
    expect(count($warehouse)===12 && isset($warehouse['power'],$warehouse['floor_load'],$warehouse['parking']) && !isset($warehouse['bathrooms'],$warehouse['generator'],$warehouse['covered_parking']),'bodega comparte doce atributos con el sujeto, parqueo agrupado y sin PH');
    expect($warehouse['power']['unit']==='kW' && $warehouse['floor_load']['unit']==='kg/m²' && $warehouse['height']['unit']==='m','bodega conserva unidades técnicas sin sustituir mediciones por puntuaciones');
    $warehousePrevious=\App\Services\SubjectFactorCapture::catalog(['unit_kind'=>'property','property_type'=>'bodega','subject_factors_json'=>json_encode(['bathrooms'=>['value'=>'2']])],[]);
    expect(isset($warehousePrevious['bathrooms']) && !isset($warehousePrevious['generator']),'bodega conserva captura retirada anterior sin introducir otros campos retirados');
    $local=\App\Services\SubjectFactorCapture::catalog(['unit_kind'=>'property','property_type'=>'local'],[]);
    expect(count($local)===9 && isset($local['commercial_strength'],$local['parking']) && !isset($local['bathrooms'],$local['floor'],$local['covered_parking'],$local['generator']),'local comparte nueve atributos aprobados con el sujeto, sin PH ni parqueo duplicado');
    expect(\App\Services\SubjectFactorCapture::code('Baja',$local['commercial_strength'])==='Código: 0' && \App\Services\SubjectFactorCapture::code('Alta',$local['commercial_strength'])==='Código: 2','fuerza comercial codifica baja a alta sin sustituir los datos originales');
    $previous=\App\Services\SubjectFactorCapture::catalog(['unit_kind'=>'property','property_type'=>'local','subject_factors_json'=>json_encode(['bathrooms'=>['value'=>'2']])],[]);
    expect(isset($previous['bathrooms']) && !isset($previous['deposit']),'local conserva únicamente los atributos retirados que ya tenían captura');
    expect(\App\Services\SubjectFactorCapture::code('Básico / económico',$finish)==='Código: 0' && \App\Services\SubjectFactorCapture::code('Superior / lujo',$finish)==='Código: 4' && \App\Services\SubjectFactorCapture::code('Obra gris',$finish)==='Pendiente','acabados tienen cinco niveles definidos sin confundir obra gris con calidad');
})();
