<?php
declare(strict_types=1);
(static function():void {
    $primary=static fn($catalog)=>array_filter($catalog,static fn($factor)=>empty($factor['supplemental']));
    $post=['label'=>'Jacuzzi verificado de prueba','why'=>'Presencia comprobada en la unidad','unit'=>'sí/no','kind'=>'binary','categories'=>'No / Sí','group'=>'Unidad privada','types'=>['apartamento','casa']];
    $data=\App\Services\UserResearchFactorInput::input($post);
    expect($data['categories']==="No\nSí" && $data['types']===['apartamento','casa'],'nuevo binario conserva ausencia cero y presencia uno para todos sus tipos');
    expectStatus(422,fn()=>\App\Services\UserResearchFactorInput::input(array_replace($post,['types'=>['inventado']])),'no admite asignar factor a tipo inexistente');
    expectStatus(422,fn()=>\App\Services\UserResearchFactorInput::input(array_replace($post,['label'=>'Baños'])),'nombre repetido orienta a editar el existente');
    expectStatus(422,fn()=>\App\Services\UserResearchFactorInput::input(array_replace($post,['kind'=>'ordinal','categories'=>"No\nPendiente\nSí"])),'desconocido no se convierte en un nivel de jerarquía');
    expectStatus(422,fn()=>\App\Services\UserResearchFactorInput::input(array_replace($post,['kind'=>'ordinal','categories'=>"No\nno"])),'rechaza niveles repetidos aunque cambien mayúsculas');
    expectStatus(422,fn()=>\App\Services\UserResearchFactorInput::input($post,'area'),'bases de cálculo no se redefinen como atributos');
    $base=\App\Services\ResearchFactorCatalog::all()['age'];
    expectStatus(422,fn()=>\App\Services\UserResearchFactorInput::input(array_replace($post,['label'=>'Edad','unit'=>'meses','kind'=>'numeric']),'age'),'no cambia años por meses sobre calificaciones previas');
    $office=\App\Services\ResearchFactorCatalog::forType('oficina');
    expect(count(array_diff_key($office,array_flip(['area','destination'])))===13 && $office['corner']['group']==='Unidad privada','oficina queda con trece atributos aprobados y esquina privada');
    $old=['unit_kind'=>'property','property_type'=>'oficina','subject_factors_json'=>json_encode(['air_conditioning'=>['value'=>'Sí']])];
    expect(isset(\App\Services\SubjectFactorCapture::catalog($old,[])['air_conditioning']),'retirar aire acondicionado no elimina captura histórica del sujeto');
    $finish=\App\Services\ResearchFactorCatalog::all()['finish_quality'];
    $building=\App\Services\SubjectFactorCapture::catalog(['unit_kind'=>'property','property_type'=>'edificio'],[]);
    expect(count($primary($building))===9 && isset($building['elevator_count'],$building['access_ramp']) && !isset($building['elevator'],$building['bathrooms'],$building['covered_parking']),'edificio comparte nueve atributos aprobados y parqueo agrupado con el sujeto');
    expect($building['elevator_count']['kind']==='numeric' && $building['elevator_count']['unit']==='cantidad' && $building['levels']['label']==='Número de pisos','edificio distingue cantidad de ascensores operativos y pisos de indicadores binarios');
    $buildingPrevious=\App\Services\SubjectFactorCapture::catalog(['unit_kind'=>'property','property_type'=>'edificio','subject_factors_json'=>json_encode(['elevator'=>['value'=>'Sí']])],[]);
    expect(isset($buildingPrevious['elevator'],$buildingPrevious['elevator_count']) && $buildingPrevious['elevator']['sample']!==$buildingPrevious['elevator_count']['sample'],'ascensor histórico se conserva sin convertir presencia en cantidad operativa');
    $consulting=\App\Services\SubjectFactorCapture::catalog(['unit_kind'=>'property','property_type'=>'consultorio'],[]);
    $officeSubject=\App\Services\SubjectFactorCapture::catalog(['unit_kind'=>'property','property_type'=>'oficina'],[]);
    expect(count($primary($consulting))===14 && array_diff_key($primary($consulting),['access_ramp'=>true])===$primary($officeSubject),'consultorio comparte exactamente los atributos y escalas de oficina más rampa');
    expect(\App\Services\SubjectFactorCapture::code('No',$consulting['access_ramp'])==='Código: 0' && \App\Services\SubjectFactorCapture::code('Sí',$consulting['access_ramp'])==='Código: 1' && \App\Services\SubjectFactorCapture::code('',$consulting['access_ramp'])==='Pendiente','rampa tiene codificación binaria y desconocido no equivale a ausencia');
    $consultingPrevious=\App\Services\SubjectFactorCapture::catalog(['unit_kind'=>'property','property_type'=>'consultorio','subject_factors_json'=>json_encode(['accessible'=>['value'=>'Sí']])],[]);
    expect(isset($consultingPrevious['accessible'],$consultingPrevious['access_ramp']) && $consultingPrevious['accessible']['sample']!==$consultingPrevious['access_ramp']['sample'],'accesibilidad histórica no se convierte automáticamente en rampa');
    $land=\App\Services\SubjectFactorCapture::catalog(['unit_kind'=>'property','property_type'=>'lote'],[]);
    expect(count($primary($land))===6 && isset($land['front_exposure'],$land['public_services']) && !isset($land['corner'],$land['water'],$land['electricity'],$land['sewer']),'lote comparte seis atributos con el sujeto y agrupa frentes y servicios');
    expect(\App\Services\SubjectFactorCapture::code('Medianero',$land['front_exposure'])==='Código: 0' && \App\Services\SubjectFactorCapture::code('Tres frentes',$land['front_exposure'])==='Código: 2' && \App\Services\SubjectFactorCapture::code('Parciales',$land['public_services'])==='Código: 1','lote aplica jerarquías acordadas sin códigos para desconocidos');
    $landPart=\App\Services\ResearchFactorCatalog::forType('lote','terreno');
    expect(isset($landPart['public_services'],$landPart['front_exposure'],$landPart['land']),'recorrido de terreno conserva las clasificaciones agrupadas y su base de área');
    $landPrevious=\App\Services\SubjectFactorCapture::catalog(['unit_kind'=>'property','property_type'=>'lote','subject_factors_json'=>json_encode(['water'=>['value'=>'Sí']])],[]);
    expect(isset($landPrevious['water'],$landPrevious['public_services']) && !isset($landPrevious['electricity']),'lote conserva agua histórica sin inventar servicios completos ni otros datos antiguos');
    $warehouse=\App\Services\SubjectFactorCapture::catalog(['unit_kind'=>'property','property_type'=>'bodega'],[]);
    expect(count($primary($warehouse))===12 && isset($warehouse['power'],$warehouse['floor_load'],$warehouse['parking']) && !isset($warehouse['bathrooms'],$warehouse['generator'],$warehouse['covered_parking']),'bodega comparte doce atributos con el sujeto, parqueo agrupado y sin PH');
    expect($warehouse['power']['unit']==='kW' && $warehouse['floor_load']['unit']==='kg/m²' && $warehouse['height']['unit']==='m','bodega conserva unidades técnicas sin sustituir mediciones por puntuaciones');
    $warehousePrevious=\App\Services\SubjectFactorCapture::catalog(['unit_kind'=>'property','property_type'=>'bodega','subject_factors_json'=>json_encode(['bathrooms'=>['value'=>'2']])],[]);
    expect(isset($warehousePrevious['bathrooms']) && !isset($warehousePrevious['generator']),'bodega conserva captura retirada anterior sin introducir otros campos retirados');
    $local=\App\Services\SubjectFactorCapture::catalog(['unit_kind'=>'property','property_type'=>'local'],[]);
    expect(count($primary($local))===9 && isset($local['commercial_strength'],$local['parking']) && !isset($local['bathrooms'],$local['floor'],$local['covered_parking'],$local['generator']),'local comparte nueve atributos aprobados con el sujeto, sin PH ni parqueo duplicado');
    expect(\App\Services\SubjectFactorCapture::code('Baja',$local['commercial_strength'])==='Código: 0' && \App\Services\SubjectFactorCapture::code('Alta',$local['commercial_strength'])==='Código: 2','fuerza comercial codifica baja a alta sin sustituir los datos originales');
    $previous=\App\Services\SubjectFactorCapture::catalog(['unit_kind'=>'property','property_type'=>'local','subject_factors_json'=>json_encode(['bathrooms'=>['value'=>'2']])],[]);
    expect(isset($previous['bathrooms']) && !isset($previous['deposit']),'local conserva únicamente los atributos retirados que ya tenían captura');
    expect(\App\Services\SubjectFactorCapture::code('Básico / económico',$finish)==='Código: 0' && \App\Services\SubjectFactorCapture::code('Superior / lujo',$finish)==='Código: 4' && \App\Services\SubjectFactorCapture::code('Obra gris',$finish)==='Pendiente','acabados tienen cinco niveles definidos sin confundir obra gris con calidad');
})();
