<?php
declare(strict_types=1);

// method, path expression, controller, action, requires authentication
return [
    ['GET', '#^/login$#', 'auth', 'login', false],
    ['POST', '#^/login$#', 'auth', 'attempt', false],
    ['GET', '#^/diagnostico/login$#', 'diagnostics', 'login', false],
    ['POST', '#^/logout$#', 'auth', 'logout', true],
    ['GET', '#^/valuaciones$#', 'valuations', 'index', true],
    ['GET', '#^/maestros$#', 'masters', 'index', true],
    ['POST', '#^/maestros/peritos$#', 'masters', 'createAppraiser', true],
    ['POST', '#^/maestros/departamentos$#', 'masters', 'createDepartment', true],
    ['POST', '#^/maestros/ciudades$#', 'masters', 'createCity', true],
    ['POST', '#^/maestros/localidades$#', 'masters', 'createLocality', true],
    ['POST', '#^/maestros/barrios$#', 'masters', 'createNeighborhood', true],
    ['GET', '#^/maestros/peritos/([a-f0-9]{32})/raa$#', 'masters', 'raaFile', true],
    ['GET', '#^/$#', 'appraisals', 'index', true],
    ['GET', '#^/normas-tecnicas-sectoriales$#', 'standards', 'index', true],
    ['GET', '#^/marco-juridico-valuatorio$#', 'legal', 'index', true],
    ['GET', '#^/normas-internacionales-valuacion$#', 'international', 'index', true],
    ['GET', '#^/normas-niif$#', 'ifrs', 'index', true],
    ['GET', '#^/tipologias-constructivas-igac$#', 'typologies', 'index', true],
    ['POST', '#^/normas-tecnicas-sectoriales/importar$#', 'standards', 'import', true],
    ['POST', '#^/marco-juridico-valuatorio/importar$#', 'legal', 'import', true],
    ['POST', '#^/marco-juridico-valuatorio/([a-z0-9-]+)/importar$#', 'legal', 'importFile', true],
    ['POST', '#^/normas-internacionales-valuacion/([a-z0-9-]+)/importar$#', 'international', 'importFile', true],
    ['POST', '#^/normas-niif/([a-z0-9-]+)/importar$#', 'ifrs', 'importFile', true],
    ['GET', '#^/normas-tecnicas-sectoriales/([a-z0-9-]+)$#', 'standards', 'show', true],
    ['GET', '#^/normas-tecnicas-sectoriales/([a-z0-9-]+)/archivo$#', 'standards', 'file', true],
    ['GET', '#^/marco-juridico-valuatorio/([a-z0-9-]+)/archivo$#', 'legal', 'file', true],
    ['GET', '#^/normas-internacionales-valuacion/([a-z0-9-]+)/archivo$#', 'international', 'file', true],
    ['GET', '#^/normas-niif/([a-z0-9-]+)/archivo$#', 'ifrs', 'file', true],
    ['POST', '#^/avaluos$#', 'appraisals', 'create', true],
    ['GET', '#^/avaluos/([a-f0-9]{32})/capitulo-0$#', 'appraisals', 'chapterZero', true],
    ['POST', '#^/avaluos/([a-f0-9]{32})/capitulo-0$#', 'appraisals', 'saveChapterZero', true],
    ['GET', '#^/avaluos/([a-f0-9]{32})/bien-sujeto$#', 'appraisals', 'subject', true],
    ['POST', '#^/avaluos/([a-f0-9]{32})/bien-sujeto/preclasificacion$#', 'appraisals', 'saveSubjectPreclassification', true],
    ['POST', '#^/avaluos/([a-f0-9]{32})/bien-sujeto/unidades$#', 'appraisals', 'saveSubjectUnits', true],
    ['POST', '#^/avaluos/([a-f0-9]{32})/bien-sujeto/fotos$#', 'appraisals', 'uploadSubjectPhotos', true],
    ['POST', '#^/avaluos/([a-f0-9]{32})/fotos/([a-f0-9]{32})/eliminar$#', 'appraisals', 'deletePhoto', true],
    ['GET', '#^/avaluos/([a-f0-9]{32})/fotos/([a-f0-9]{32})$#', 'appraisals', 'photo', true],
    ['GET', '#^/avaluos/([a-f0-9]{32})$#', 'appraisals', 'edit', true],
    ['POST', '#^/avaluos/([a-f0-9]{32})/borrador$#', 'appraisals', 'save', true],
];
