<label class="flex min-h-11 items-center gap-3"><input type="checkbox" name="directed" value="si" <?= ($formData['directed'] ?? '') === 'si' ? 'checked' : '' ?>>Este dictamen va dirigido a un juzgado.</label>
<label class="label">Fecha del dictamen<input class="input" type="date" name="report_date" value="<?= e($formData['report_date'] ?? '') ?>"><span class="text-xs">Define las ventanas de 10 y 4 años para los antecedentes.</span></label>
<?php foreach (['court' => 'Juzgado o despacho destinatario', 'docket' => 'Radicado o identificación del proceso', 'parties' => 'Nombre de las partes', 'lawyers' => 'Nombre de los apoderados', 'matter' => 'Materia y objeto del dictamen', 'participants' => 'Otros participantes: identidad, profesión y soportes de idoneidad (226.1 y 3)', 'methods' => 'Exámenes, métodos, experimentos e investigaciones realizados', 'documents' => 'Relación de documentos e información usados y anexos que acompañan el dictamen (226.10)', 'independence' => 'Declaración del perito sobre independencia, convicción profesional e imparcialidad (226 y 235)', 'receipt' => 'Referencia o ubicación de la constancia de presentación al juzgado'] as $key => $label): ?>
    <label class="label"><?= e($label) ?><textarea class="input" name="<?= e($key) ?>" rows="3" maxlength="12000" placeholder="<?= e($label) ?>. Si no aplica, explica por qué."><?= e($formData[$key] ?? '') ?></textarea></label>
<?php endforeach; ?>
<?php foreach (['same_party' => '¿Fue designado en procesos anteriores o en curso por la misma parte o apoderado? (226.6)', 'exclusion' => '¿Se encuentra incurso en causales del artículo 50, en lo pertinente? (226.7)', 'previous' => '¿Los métodos difieren de los empleados en peritajes anteriores sobre la misma materia? (226.8)', 'regular' => '¿Los métodos difieren de los que usa habitualmente en su profesión u oficio? (226.9)'] as $key => $label): ?>
    <fieldset class="space-y-3 rounded-xl border p-4"><legend class="font-semibold"><?= e($label) ?></legend>
        <label class="label">Declaración del perito<select class="input" name="<?= e($key) ?>"><option value="">Selecciona después de verificar</option><?php foreach (['si' => 'Sí', 'no' => 'No'] + ($key === 'previous' ? ['sin_anteriores' => 'No tengo peritajes anteriores sobre esa materia'] : []) as $value => $text): ?><option value="<?= e($value) ?>" <?= ($formData[$key] ?? '') === $value ? 'selected' : '' ?>><?= e($text) ?></option><?php endforeach; ?></select></label>
        <label class="label">Detalle y justificación<textarea class="input" rows="3" name="<?= e($key) ?>_detail" maxlength="12000" placeholder="Relaciona procesos y su objeto, circunstancias o justifica la variación, según corresponda."><?= e($formData[$key . '_detail'] ?? '') ?></textarea></label>
    </fieldset>
<?php endforeach; ?>
<fieldset class="space-y-2 rounded-xl border p-4"><legend class="font-semibold">Publicaciones relacionadas con esta materia</legend><p class="text-sm">Marca las pertinentes. La exportación aplicará además el período de 10 años a la fecha del dictamen.</p>
    <?php foreach ($profile['data']['history'] ?? [] as $publication): if (($publication['kind'] ?? '') !== 'publication') continue; $ref = App\Services\JudicialExpertReport::publicationKey($publication); ?>
        <label class="flex min-h-11 items-center gap-3"><input type="checkbox" name="publication_refs[]" value="<?= e($ref) ?>" <?= in_array($ref, $formData['publication_refs'] ?? [], true) ? 'checked' : '' ?>><?= e(($publication['date'] ?? '') . ' · ' . ($publication['title'] ?? 'Sin título')) ?></label>
    <?php endforeach; ?>
    <p class="text-sm">Si falta alguna publicación, agrégala primero en el maestro del perito.</p>
</fieldset>
<label class="flex min-h-11 items-start gap-3"><input class="mt-1" type="checkbox" name="history_reviewed" value="si" <?= ($formData['history_reviewed'] ?? '') === 'si' ? 'checked' : '' ?>>El perito verificó que los antecedentes están completos y seleccionó las publicaciones pertinentes; confirma la ausencia de antecedentes cuando la relación correspondiente esté vacía.</label>
<label class="flex min-h-11 items-start gap-3"><input class="mt-1" type="checkbox" name="annexes_reviewed" value="si" <?= ($formData['annexes_reviewed'] ?? '') === 'si' ? 'checked' : '' ?>>Verifiqué los títulos, documentos de idoneidad y demás soportes y los adjunté al dictamen. Esta ficha solo conserva sus referencias.</label>
