<?php
declare(strict_types=1);
use App\Database\Schema;

return static function (Schema $schema): void {
    $schema->db->exec("CREATE TABLE IF NOT EXISTS appraisal_subjects (
        appraisal_id CHAR(32) PRIMARY KEY,
        owner_id BIGINT UNSIGNED NOT NULL,
        department_id CHAR(32) NULL,
        department_name VARCHAR(120) NOT NULL DEFAULT '',
        city_id CHAR(32) NULL,
        city_name VARCHAR(140) NOT NULL DEFAULT '',
        neighborhood_id CHAR(32) NULL,
        neighborhood_name VARCHAR(160) NOT NULL DEFAULT '',
        locality_name VARCHAR(160) NOT NULL DEFAULT '',
        commune_ucg VARCHAR(80) NOT NULL DEFAULT '',
        zone_sector VARCHAR(120) NOT NULL DEFAULT '',
        point_reference VARCHAR(220) NOT NULL DEFAULT '',
        address VARCHAR(220) NOT NULL DEFAULT '',
        alternate_nomenclature VARCHAR(160) NOT NULL DEFAULT '',
        horizontal_property VARCHAR(30) NOT NULL DEFAULT '',
        centrality VARCHAR(40) NOT NULL DEFAULT '',
        immediate_environment VARCHAR(80) NOT NULL DEFAULT '',
        stratum VARCHAR(20) NOT NULL DEFAULT '',
        property_registry VARCHAR(80) NOT NULL DEFAULT '',
        cadastral_reference VARCHAR(120) NOT NULL DEFAULT '',
        registry_office VARCHAR(120) NOT NULL DEFAULT '',
        urban_license VARCHAR(80) NOT NULL DEFAULT '',
        permitted_use VARCHAR(80) NOT NULL DEFAULT '',
        urban_treatment VARCHAR(100) NOT NULL DEFAULT '',
        restrictions VARCHAR(220) NOT NULL DEFAULT '',
        legal_urban_affectations VARCHAR(220) NOT NULL DEFAULT '',
        road_condition VARCHAR(80) NOT NULL DEFAULT '',
        access_facility VARCHAR(40) NOT NULL DEFAULT '',
        transport_connectivity VARCHAR(40) NOT NULL DEFAULT '',
        loading_unloading VARCHAR(40) NOT NULL DEFAULT '',
        current_use VARCHAR(80) NOT NULL DEFAULT '',
        main_potential_use VARCHAR(80) NOT NULL DEFAULT '',
        complementary_potential_uses VARCHAR(160) NOT NULL DEFAULT '',
        main_complementary_activity VARCHAR(100) NOT NULL DEFAULT '',
        secondary_complementary_activities VARCHAR(160) NOT NULL DEFAULT '',
        current_occupation VARCHAR(40) NOT NULL DEFAULT '',
        water_service VARCHAR(40) NOT NULL DEFAULT '',
        energy_service VARCHAR(40) NOT NULL DEFAULT '',
        gas_service VARCHAR(40) NOT NULL DEFAULT '',
        sewer_service VARCHAR(40) NOT NULL DEFAULT '',
        internet_service VARCHAR(40) NOT NULL DEFAULT '',
        service_continuity VARCHAR(40) NOT NULL DEFAULT '',
        subject_reference_date DATE NULL,
        latitude VARCHAR(40) NOT NULL DEFAULT '',
        longitude VARCHAR(40) NOT NULL DEFAULT '',
        notes TEXT NULL,
        updated_at DATETIME NOT NULL,
        INDEX idx_appraisal_subjects_owner (owner_id, updated_at)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
};
